[package]
name = "tree_sitter_gas"
description = "GNU assembler grammar for the tree-sitter parsing library"
version = "0.0.1"
keywords = ["incremental", "parsing", "asm", "gas"]
categories = ["parsing", "text-editors"]
repository = "https://github.com/sirius94/tree-sitter-gas"
edition = "2018"
license = "GPLv3"

build = "bindings/rust/build.rs"
include = [
  "bindings/rust/*",
  "grammar.js",
  "queries/*",
  "src/*",
]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter = "0.25.10"

[build-dependencies]
cc = "1.0"
