#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 111
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 48
#define ALIAS_COUNT 0
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 10
#define PRODUCTION_ID_COUNT 2

enum {
  anon_sym_COMMA = 1,
  anon_sym_DOT = 2,
  aux_sym_directive_name_token1 = 3,
  anon_sym_COLON = 4,
  anon_sym_LPAREN = 5,
  anon_sym_RPAREN = 6,
  aux_sym__displacement_expression_offset_token1 = 7,
  anon_sym_DOLLAR = 8,
  aux_sym_constant_token1 = 9,
  anon_sym_SQUOTE = 10,
  aux_sym_char_token1 = 11,
  aux_sym_char_token2 = 12,
  anon_sym_DQUOTE = 13,
  aux_sym_string_token1 = 14,
  aux_sym_string_token2 = 15,
  sym_register = 16,
  aux_sym__until_eol_token1 = 17,
  anon_sym_SLASH_STAR = 18,
  aux_sym_comment_token1 = 19,
  anon_sym_STAR_SLASH = 20,
  sym__line_comment = 21,
  sym__inline_space = 22,
  sym_source_file = 23,
  sym__statement = 24,
  sym_directive = 25,
  sym_directive_name = 26,
  sym_directive_arg = 27,
  sym_instruction = 28,
  sym_instruction_name = 29,
  sym__operand = 30,
  sym__displacement_expression = 31,
  sym__displacement_expression_offset = 32,
  sym_constant = 33,
  sym_char = 34,
  sym_string = 35,
  sym_number = 36,
  sym_symbol = 37,
  sym__until_eol = 38,
  sym_comment = 39,
  sym__block_comment = 40,
  aux_sym_source_file_repeat1 = 41,
  aux_sym_directive_repeat1 = 42,
  aux_sym_instruction_repeat1 = 43,
  aux_sym_string_repeat1 = 44,
  aux_sym__until_eol_repeat1 = 45,
  aux_sym_comment_repeat1 = 46,
  aux_sym__block_comment_repeat1 = 47,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COMMA] = ",",
  [anon_sym_DOT] = ".",
  [aux_sym_directive_name_token1] = "directive_name_token1",
  [anon_sym_COLON] = ":",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [aux_sym__displacement_expression_offset_token1] = "_displacement_expression_offset_token1",
  [anon_sym_DOLLAR] = "$",
  [aux_sym_constant_token1] = "constant_token1",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_char_token1] = "char_token1",
  [aux_sym_char_token2] = "char_token2",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [aux_sym_string_token2] = "string_token2",
  [sym_register] = "register",
  [aux_sym__until_eol_token1] = "_until_eol_token1",
  [anon_sym_SLASH_STAR] = "/*",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_STAR_SLASH] = "*/",
  [sym__line_comment] = "comment",
  [sym__inline_space] = "_inline_space",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_directive] = "directive",
  [sym_directive_name] = "directive_name",
  [sym_directive_arg] = "directive_arg",
  [sym_instruction] = "instruction",
  [sym_instruction_name] = "instruction_name",
  [sym__operand] = "_operand",
  [sym__displacement_expression] = "_displacement_expression",
  [sym__displacement_expression_offset] = "_displacement_expression_offset",
  [sym_constant] = "constant",
  [sym_char] = "char",
  [sym_string] = "string",
  [sym_number] = "number",
  [sym_symbol] = "symbol",
  [sym__until_eol] = "_until_eol",
  [sym_comment] = "comment",
  [sym__block_comment] = "comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_directive_repeat1] = "directive_repeat1",
  [aux_sym_instruction_repeat1] = "instruction_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym__until_eol_repeat1] = "_until_eol_repeat1",
  [aux_sym_comment_repeat1] = "comment_repeat1",
  [aux_sym__block_comment_repeat1] = "_block_comment_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_DOT] = anon_sym_DOT,
  [aux_sym_directive_name_token1] = aux_sym_directive_name_token1,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [aux_sym__displacement_expression_offset_token1] = aux_sym__displacement_expression_offset_token1,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [aux_sym_constant_token1] = aux_sym_constant_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_char_token1] = aux_sym_char_token1,
  [aux_sym_char_token2] = aux_sym_char_token2,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [sym_register] = sym_register,
  [aux_sym__until_eol_token1] = aux_sym__until_eol_token1,
  [anon_sym_SLASH_STAR] = anon_sym_SLASH_STAR,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_STAR_SLASH] = anon_sym_STAR_SLASH,
  [sym__line_comment] = sym_comment,
  [sym__inline_space] = sym__inline_space,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_directive] = sym_directive,
  [sym_directive_name] = sym_directive_name,
  [sym_directive_arg] = sym_directive_arg,
  [sym_instruction] = sym_instruction,
  [sym_instruction_name] = sym_instruction_name,
  [sym__operand] = sym__operand,
  [sym__displacement_expression] = sym__displacement_expression,
  [sym__displacement_expression_offset] = sym__displacement_expression_offset,
  [sym_constant] = sym_constant,
  [sym_char] = sym_char,
  [sym_string] = sym_string,
  [sym_number] = sym_number,
  [sym_symbol] = sym_symbol,
  [sym__until_eol] = sym__until_eol,
  [sym_comment] = sym_comment,
  [sym__block_comment] = sym_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_directive_repeat1] = aux_sym_directive_repeat1,
  [aux_sym_instruction_repeat1] = aux_sym_instruction_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym__until_eol_repeat1] = aux_sym__until_eol_repeat1,
  [aux_sym_comment_repeat1] = aux_sym_comment_repeat1,
  [aux_sym__block_comment_repeat1] = aux_sym__block_comment_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_directive_name_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__displacement_expression_offset_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_constant_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_char_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_char_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_register] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__until_eol_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_STAR_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym__line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__inline_space] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_directive_name] = {
    .visible = true,
    .named = true,
  },
  [sym_directive_arg] = {
    .visible = true,
    .named = true,
  },
  [sym_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym_instruction_name] = {
    .visible = true,
    .named = true,
  },
  [sym__operand] = {
    .visible = false,
    .named = true,
  },
  [sym__displacement_expression] = {
    .visible = false,
    .named = true,
  },
  [sym__displacement_expression_offset] = {
    .visible = false,
    .named = true,
  },
  [sym_constant] = {
    .visible = true,
    .named = true,
  },
  [sym_char] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym__until_eol] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__block_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_directive_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_instruction_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__until_eol_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__block_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = sym_number,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 54,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 26,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 51,
  [73] = 73,
  [74] = 74,
  [75] = 30,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 57,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 89,
  [110] = 76,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(20);
      if (lookahead == '\n') ADVANCE(46);
      if (lookahead == '\r') ADVANCE(46);
      if (lookahead == '"') ADVANCE(49);
      if (lookahead == '$') ADVANCE(38);
      if (lookahead == '\'') ADVANCE(44);
      if (lookahead == '(') ADVANCE(25);
      if (lookahead == ')') ADVANCE(26);
      if (lookahead == ',') ADVANCE(21);
      if (lookahead == '.') ADVANCE(22);
      if (lookahead == '/') ADVANCE(47);
      if (lookahead == ':') ADVANCE(24);
      if (lookahead == '\\') ADVANCE(59);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(48);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      if (lookahead != 0) ADVANCE(46);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(57);
      if (lookahead == '\r') ADVANCE(56);
      if (lookahead == '*') ADVANCE(61);
      if (lookahead == '/') ADVANCE(60);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(62);
      if (lookahead != 0) ADVANCE(59);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(49);
      if (lookahead == '$') ADVANCE(38);
      if (lookahead == '%') ADVANCE(18);
      if (lookahead == '\'') ADVANCE(44);
      if (lookahead == '(') ADVANCE(25);
      if (lookahead == '-') ADVANCE(8);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == '0') ADVANCE(31);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(65);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(35);
      if (lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(49);
      if (lookahead == '%') ADVANCE(18);
      if (lookahead == '\'') ADVANCE(44);
      if (lookahead == '(') ADVANCE(25);
      if (lookahead == '-') ADVANCE(8);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == '0') ADVANCE(31);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(65);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(35);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(49);
      if (lookahead == '/') ADVANCE(52);
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(51);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(58);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(61);
      if (lookahead == '/') ADVANCE(60);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(47);
      if (lookahead == '\\') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(46);
      END_STATE();
    case 8:
      if (lookahead == '0') ADVANCE(32);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(35);
      END_STATE();
    case 9:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      END_STATE();
    case 10:
      if (lookahead == '"' ||
          lookahead == '\\' ||
          lookahead == 'b' ||
          lookahead == 'f' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(50);
      if (lookahead == 'x') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 11:
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '\\' ||
          lookahead == 'b' ||
          lookahead == 'f' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(45);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 15:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(37);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(50);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(16);
      END_STATE();
    case 18:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 19:
      if (eof) ADVANCE(20);
      if (lookahead == '\n') ADVANCE(57);
      if (lookahead == '\r') ADVANCE(56);
      if (lookahead == '#') ADVANCE(64);
      if (lookahead == '%') ADVANCE(18);
      if (lookahead == '\'') ADVANCE(44);
      if (lookahead == '(') ADVANCE(25);
      if (lookahead == ')') ADVANCE(26);
      if (lookahead == ',') ADVANCE(21);
      if (lookahead == '.') ADVANCE(22);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == ':') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(65);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_directive_name_token1);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym__displacement_expression_offset_token1);
      if (lookahead == '.') ADVANCE(42);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(41);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(9);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(28);
      if (('2' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym__displacement_expression_offset_token1);
      if (lookahead == '.') ADVANCE(42);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(9);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(28);
      if (('2' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym__displacement_expression_offset_token1);
      if (lookahead == '.') ADVANCE(42);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(30);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym__displacement_expression_offset_token1);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(37);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym__displacement_expression_offset_token1);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(27);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(34);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym__displacement_expression_offset_token1);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(33);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(34);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym__displacement_expression_offset_token1);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym__displacement_expression_offset_token1);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym__displacement_expression_offset_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym__displacement_expression_offset_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(37);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym__displacement_expression_offset_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_constant_token1);
      if (lookahead == '.') ADVANCE(42);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(41);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_constant_token1);
      if (lookahead == '.') ADVANCE(42);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(41);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(30);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_constant_token1);
      if (lookahead == '.') ADVANCE(42);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_constant_token1);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_constant_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_char_token1);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_char_token2);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_char_token2);
      if (lookahead == '*') ADVANCE(58);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_char_token2);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(65);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_string_token2);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '*') ADVANCE(58);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(65);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_register);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym__until_eol_token1);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym__until_eol_token1);
      if (lookahead == '\n') ADVANCE(55);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym__until_eol_token1);
      if (lookahead == '\r') ADVANCE(55);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '*') ADVANCE(58);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '/') ADVANCE(63);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(65);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_STAR_SLASH);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym__line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym__inline_space);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(65);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 19},
  [2] = {.lex_state = 2},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 19},
  [5] = {.lex_state = 19},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 19},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 19},
  [15] = {.lex_state = 19},
  [16] = {.lex_state = 19},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 19},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 19},
  [21] = {.lex_state = 3},
  [22] = {.lex_state = 19},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 19},
  [25] = {.lex_state = 4},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 19},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 19},
  [31] = {.lex_state = 19},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 4},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 4},
  [36] = {.lex_state = 19},
  [37] = {.lex_state = 19},
  [38] = {.lex_state = 3},
  [39] = {.lex_state = 19},
  [40] = {.lex_state = 19},
  [41] = {.lex_state = 19},
  [42] = {.lex_state = 19},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 19},
  [47] = {.lex_state = 3},
  [48] = {.lex_state = 3},
  [49] = {.lex_state = 19},
  [50] = {.lex_state = 19},
  [51] = {.lex_state = 6},
  [52] = {.lex_state = 19},
  [53] = {.lex_state = 4},
  [54] = {.lex_state = 6},
  [55] = {.lex_state = 6},
  [56] = {.lex_state = 19},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 19},
  [59] = {.lex_state = 19},
  [60] = {.lex_state = 19},
  [61] = {.lex_state = 19},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 19},
  [64] = {.lex_state = 6},
  [65] = {.lex_state = 19},
  [66] = {.lex_state = 19},
  [67] = {.lex_state = 19},
  [68] = {.lex_state = 19},
  [69] = {.lex_state = 19},
  [70] = {.lex_state = 19},
  [71] = {.lex_state = 19},
  [72] = {.lex_state = 6},
  [73] = {.lex_state = 19},
  [74] = {.lex_state = 19},
  [75] = {.lex_state = 19},
  [76] = {.lex_state = 19},
  [77] = {.lex_state = 19},
  [78] = {.lex_state = 19},
  [79] = {.lex_state = 19},
  [80] = {.lex_state = 19},
  [81] = {.lex_state = 19},
  [82] = {.lex_state = 19},
  [83] = {.lex_state = 19},
  [84] = {.lex_state = 7},
  [85] = {.lex_state = 19},
  [86] = {.lex_state = 19},
  [87] = {.lex_state = 6},
  [88] = {.lex_state = 19},
  [89] = {.lex_state = 19},
  [90] = {.lex_state = 19},
  [91] = {.lex_state = 19},
  [92] = {.lex_state = 19},
  [93] = {.lex_state = 19},
  [94] = {.lex_state = 3},
  [95] = {.lex_state = 19},
  [96] = {.lex_state = 19},
  [97] = {.lex_state = 19},
  [98] = {.lex_state = 19},
  [99] = {.lex_state = 19},
  [100] = {.lex_state = 19},
  [101] = {.lex_state = 19},
  [102] = {.lex_state = 19},
  [103] = {.lex_state = 19},
  [104] = {.lex_state = 19},
  [105] = {.lex_state = 19},
  [106] = {.lex_state = 19},
  [107] = {.lex_state = 19},
  [108] = {.lex_state = 19},
  [109] = {(TSStateId)(-1)},
  [110] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [aux_sym_directive_name_token1] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [aux_sym_char_token2] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [aux_sym_string_token2] = ACTIONS(1),
    [anon_sym_SLASH_STAR] = ACTIONS(3),
    [aux_sym_comment_token1] = ACTIONS(1),
    [sym__inline_space] = ACTIONS(5),
  },
  [1] = {
    [sym_source_file] = STATE(96),
    [sym__statement] = STATE(9),
    [sym_directive] = STATE(9),
    [sym_directive_name] = STATE(105),
    [sym_instruction] = STATE(9),
    [sym_instruction_name] = STATE(108),
    [sym__until_eol] = STATE(5),
    [sym_comment] = STATE(1),
    [sym__block_comment] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(5),
    [aux_sym__until_eol_repeat1] = STATE(36),
    [ts_builtin_sym_end] = ACTIONS(7),
    [anon_sym_DOT] = ACTIONS(9),
    [aux_sym_directive_name_token1] = ACTIONS(11),
    [aux_sym__until_eol_token1] = ACTIONS(13),
    [anon_sym_SLASH_STAR] = ACTIONS(15),
    [sym__line_comment] = ACTIONS(13),
    [sym__inline_space] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(19), 1,
      aux_sym_directive_name_token1,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      aux_sym__displacement_expression_offset_token1,
    ACTIONS(25), 1,
      anon_sym_DOLLAR,
    ACTIONS(27), 1,
      aux_sym_constant_token1,
    ACTIONS(29), 1,
      anon_sym_SQUOTE,
    ACTIONS(31), 1,
      anon_sym_DQUOTE,
    ACTIONS(33), 1,
      sym_register,
    STATE(2), 1,
      sym_comment,
    STATE(42), 1,
      sym_symbol,
    STATE(100), 1,
      sym__displacement_expression_offset,
    STATE(40), 6,
      sym__operand,
      sym__displacement_expression,
      sym_constant,
      sym_char,
      sym_string,
      sym_number,
  [48] = 14,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(19), 1,
      aux_sym_directive_name_token1,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      aux_sym__displacement_expression_offset_token1,
    ACTIONS(25), 1,
      anon_sym_DOLLAR,
    ACTIONS(27), 1,
      aux_sym_constant_token1,
    ACTIONS(29), 1,
      anon_sym_SQUOTE,
    ACTIONS(31), 1,
      anon_sym_DQUOTE,
    ACTIONS(33), 1,
      sym_register,
    STATE(3), 1,
      sym_comment,
    STATE(42), 1,
      sym_symbol,
    STATE(100), 1,
      sym__displacement_expression_offset,
    STATE(73), 6,
      sym__operand,
      sym__displacement_expression,
      sym_constant,
      sym_char,
      sym_string,
      sym_number,
  [96] = 11,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(35), 1,
      ts_builtin_sym_end,
    ACTIONS(37), 1,
      anon_sym_DOT,
    ACTIONS(40), 1,
      aux_sym_directive_name_token1,
    ACTIONS(46), 1,
      anon_sym_SLASH_STAR,
    STATE(36), 1,
      aux_sym__until_eol_repeat1,
    STATE(105), 1,
      sym_directive_name,
    STATE(108), 1,
      sym_instruction_name,
    ACTIONS(43), 2,
      aux_sym__until_eol_token1,
      sym__line_comment,
    STATE(9), 3,
      sym__statement,
      sym_directive,
      sym_instruction,
    STATE(4), 4,
      sym__until_eol,
      sym_comment,
      sym__block_comment,
      aux_sym_source_file_repeat1,
  [136] = 12,
    ACTIONS(9), 1,
      anon_sym_DOT,
    ACTIONS(11), 1,
      aux_sym_directive_name_token1,
    ACTIONS(15), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(49), 1,
      ts_builtin_sym_end,
    STATE(5), 1,
      sym_comment,
    STATE(36), 1,
      aux_sym__until_eol_repeat1,
    STATE(105), 1,
      sym_directive_name,
    STATE(108), 1,
      sym_instruction_name,
    ACTIONS(51), 2,
      aux_sym__until_eol_token1,
      sym__line_comment,
    STATE(4), 3,
      sym__until_eol,
      sym__block_comment,
      aux_sym_source_file_repeat1,
    STATE(9), 3,
      sym__statement,
      sym_directive,
      sym_instruction,
  [178] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(29), 1,
      anon_sym_SQUOTE,
    ACTIONS(31), 1,
      anon_sym_DQUOTE,
    ACTIONS(53), 1,
      aux_sym_directive_name_token1,
    STATE(6), 1,
      sym_comment,
    STATE(63), 1,
      sym_directive_arg,
    ACTIONS(27), 2,
      aux_sym__displacement_expression_offset_token1,
      aux_sym_constant_token1,
    STATE(56), 4,
      sym_char,
      sym_string,
      sym_number,
      sym_symbol,
  [210] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(29), 1,
      anon_sym_SQUOTE,
    ACTIONS(31), 1,
      anon_sym_DQUOTE,
    ACTIONS(53), 1,
      aux_sym_directive_name_token1,
    STATE(7), 1,
      sym_comment,
    STATE(22), 1,
      sym_directive_arg,
    ACTIONS(27), 2,
      aux_sym__displacement_expression_offset_token1,
      aux_sym_constant_token1,
    STATE(56), 4,
      sym_char,
      sym_string,
      sym_number,
      sym_symbol,
  [242] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(29), 1,
      anon_sym_SQUOTE,
    ACTIONS(31), 1,
      anon_sym_DQUOTE,
    ACTIONS(55), 1,
      aux_sym_directive_name_token1,
    STATE(8), 1,
      sym_comment,
    ACTIONS(57), 2,
      aux_sym__displacement_expression_offset_token1,
      aux_sym_constant_token1,
    STATE(49), 2,
      sym_char,
      sym_string,
  [269] = 6,
    ACTIONS(15), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      sym__inline_space,
    STATE(9), 1,
      sym_comment,
    STATE(36), 1,
      aux_sym__until_eol_repeat1,
    ACTIONS(59), 2,
      aux_sym__until_eol_token1,
      sym__line_comment,
    STATE(18), 2,
      sym__until_eol,
      sym__block_comment,
  [290] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(61), 1,
      aux_sym_directive_name_token1,
    ACTIONS(63), 1,
      aux_sym__displacement_expression_offset_token1,
    ACTIONS(65), 1,
      sym_register,
    STATE(10), 1,
      sym_comment,
    STATE(91), 1,
      sym_symbol,
    STATE(97), 1,
      sym__displacement_expression_offset,
  [315] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(61), 1,
      aux_sym_directive_name_token1,
    ACTIONS(63), 1,
      aux_sym__displacement_expression_offset_token1,
    ACTIONS(67), 1,
      anon_sym_LPAREN,
    STATE(11), 1,
      sym_comment,
    STATE(91), 1,
      sym_symbol,
    STATE(104), 1,
      sym__displacement_expression_offset,
  [340] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(61), 1,
      aux_sym_directive_name_token1,
    ACTIONS(63), 1,
      aux_sym__displacement_expression_offset_token1,
    ACTIONS(69), 1,
      sym_register,
    STATE(12), 1,
      sym_comment,
    STATE(91), 1,
      sym_symbol,
    STATE(98), 1,
      sym__displacement_expression_offset,
  [365] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(61), 1,
      aux_sym_directive_name_token1,
    ACTIONS(63), 1,
      aux_sym__displacement_expression_offset_token1,
    ACTIONS(71), 1,
      sym_register,
    STATE(13), 1,
      sym_comment,
    STATE(91), 1,
      sym_symbol,
    STATE(102), 1,
      sym__displacement_expression_offset,
  [390] = 4,
    ACTIONS(17), 1,
      sym__inline_space,
    STATE(14), 1,
      sym_comment,
    ACTIONS(75), 2,
      anon_sym_DOT,
      aux_sym_directive_name_token1,
    ACTIONS(73), 4,
      ts_builtin_sym_end,
      aux_sym__until_eol_token1,
      anon_sym_SLASH_STAR,
      sym__line_comment,
  [407] = 4,
    ACTIONS(17), 1,
      sym__inline_space,
    STATE(15), 1,
      sym_comment,
    ACTIONS(79), 2,
      anon_sym_DOT,
      aux_sym_directive_name_token1,
    ACTIONS(77), 4,
      ts_builtin_sym_end,
      aux_sym__until_eol_token1,
      anon_sym_SLASH_STAR,
      sym__line_comment,
  [424] = 4,
    ACTIONS(17), 1,
      sym__inline_space,
    STATE(16), 1,
      sym_comment,
    ACTIONS(83), 2,
      anon_sym_DOT,
      aux_sym_directive_name_token1,
    ACTIONS(81), 4,
      ts_builtin_sym_end,
      aux_sym__until_eol_token1,
      anon_sym_SLASH_STAR,
      sym__line_comment,
  [441] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(61), 1,
      aux_sym_directive_name_token1,
    ACTIONS(63), 1,
      aux_sym__displacement_expression_offset_token1,
    ACTIONS(85), 1,
      sym_register,
    STATE(17), 1,
      sym_comment,
    STATE(91), 1,
      sym_symbol,
    STATE(103), 1,
      sym__displacement_expression_offset,
  [466] = 4,
    ACTIONS(17), 1,
      sym__inline_space,
    STATE(18), 1,
      sym_comment,
    ACTIONS(87), 2,
      anon_sym_DOT,
      aux_sym_directive_name_token1,
    ACTIONS(35), 4,
      ts_builtin_sym_end,
      aux_sym__until_eol_token1,
      anon_sym_SLASH_STAR,
      sym__line_comment,
  [483] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(61), 1,
      aux_sym_directive_name_token1,
    ACTIONS(63), 1,
      aux_sym__displacement_expression_offset_token1,
    ACTIONS(89), 1,
      sym_register,
    STATE(19), 1,
      sym_comment,
    STATE(91), 1,
      sym_symbol,
    STATE(95), 1,
      sym__displacement_expression_offset,
  [508] = 4,
    ACTIONS(17), 1,
      sym__inline_space,
    STATE(20), 1,
      sym_comment,
    ACTIONS(93), 2,
      anon_sym_DOT,
      aux_sym_directive_name_token1,
    ACTIONS(91), 4,
      ts_builtin_sym_end,
      aux_sym__until_eol_token1,
      anon_sym_SLASH_STAR,
      sym__line_comment,
  [525] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(61), 1,
      aux_sym_directive_name_token1,
    ACTIONS(63), 1,
      aux_sym__displacement_expression_offset_token1,
    STATE(21), 1,
      sym_comment,
    STATE(91), 1,
      sym_symbol,
    STATE(97), 1,
      sym__displacement_expression_offset,
  [547] = 5,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(95), 1,
      anon_sym_COMMA,
    STATE(22), 1,
      sym_comment,
    STATE(41), 1,
      aux_sym_directive_repeat1,
    ACTIONS(97), 3,
      aux_sym__until_eol_token1,
      anon_sym_SLASH_STAR,
      sym__line_comment,
  [565] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      sym__inline_space,
    ACTIONS(99), 1,
      aux_sym__until_eol_token1,
    ACTIONS(101), 1,
      aux_sym_comment_token1,
    ACTIONS(103), 1,
      anon_sym_STAR_SLASH,
    STATE(23), 1,
      sym_comment,
    STATE(26), 1,
      aux_sym_comment_repeat1,
  [587] = 4,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(105), 1,
      anon_sym_COMMA,
    STATE(24), 2,
      sym_comment,
      aux_sym_directive_repeat1,
    ACTIONS(108), 3,
      aux_sym__until_eol_token1,
      anon_sym_SLASH_STAR,
      sym__line_comment,
  [603] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      sym__inline_space,
    ACTIONS(110), 1,
      anon_sym_DQUOTE,
    ACTIONS(112), 1,
      aux_sym_string_token1,
    ACTIONS(115), 1,
      aux_sym_string_token2,
    STATE(25), 2,
      sym_comment,
      aux_sym_string_repeat1,
  [623] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      sym__inline_space,
    ACTIONS(120), 1,
      aux_sym_comment_token1,
    ACTIONS(118), 2,
      aux_sym__until_eol_token1,
      anon_sym_STAR_SLASH,
    STATE(26), 2,
      sym_comment,
      aux_sym_comment_repeat1,
  [641] = 4,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(123), 1,
      anon_sym_COMMA,
    STATE(27), 2,
      sym_comment,
      aux_sym_instruction_repeat1,
    ACTIONS(126), 3,
      aux_sym__until_eol_token1,
      anon_sym_SLASH_STAR,
      sym__line_comment,
  [657] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      sym__inline_space,
    ACTIONS(128), 1,
      aux_sym__until_eol_token1,
    ACTIONS(130), 1,
      aux_sym_comment_token1,
    ACTIONS(132), 1,
      anon_sym_STAR_SLASH,
    STATE(28), 1,
      sym_comment,
    STATE(44), 1,
      aux_sym__block_comment_repeat1,
  [679] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      sym__inline_space,
    ACTIONS(128), 1,
      aux_sym__until_eol_token1,
    ACTIONS(130), 1,
      aux_sym_comment_token1,
    ACTIONS(132), 1,
      anon_sym_STAR_SLASH,
    STATE(29), 1,
      sym_comment,
    STATE(45), 1,
      aux_sym__block_comment_repeat1,
  [701] = 3,
    ACTIONS(17), 1,
      sym__inline_space,
    STATE(30), 1,
      sym_comment,
    ACTIONS(134), 5,
      anon_sym_COMMA,
      anon_sym_LPAREN,
      aux_sym__until_eol_token1,
      anon_sym_SLASH_STAR,
      sym__line_comment,
  [715] = 5,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(136), 1,
      anon_sym_COMMA,
    STATE(27), 1,
      aux_sym_instruction_repeat1,
    STATE(31), 1,
      sym_comment,
    ACTIONS(138), 3,
      aux_sym__until_eol_token1,
      anon_sym_SLASH_STAR,
      sym__line_comment,
  [733] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(61), 1,
      aux_sym_directive_name_token1,
    ACTIONS(63), 1,
      aux_sym__displacement_expression_offset_token1,
    STATE(32), 1,
      sym_comment,
    STATE(91), 1,
      sym_symbol,
    STATE(102), 1,
      sym__displacement_expression_offset,
  [755] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      sym__inline_space,
    ACTIONS(140), 1,
      anon_sym_DQUOTE,
    ACTIONS(142), 1,
      aux_sym_string_token1,
    ACTIONS(144), 1,
      aux_sym_string_token2,
    STATE(33), 1,
      sym_comment,
    STATE(35), 1,
      aux_sym_string_repeat1,
  [777] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      sym__inline_space,
    ACTIONS(128), 1,
      aux_sym__until_eol_token1,
    ACTIONS(130), 1,
      aux_sym_comment_token1,
    ACTIONS(146), 1,
      anon_sym_STAR_SLASH,
    STATE(28), 1,
      aux_sym__block_comment_repeat1,
    STATE(34), 1,
      sym_comment,
  [799] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      sym__inline_space,
    ACTIONS(142), 1,
      aux_sym_string_token1,
    ACTIONS(144), 1,
      aux_sym_string_token2,
    ACTIONS(148), 1,
      anon_sym_DQUOTE,
    STATE(25), 1,
      aux_sym_string_repeat1,
    STATE(35), 1,
      sym_comment,
  [821] = 6,
    ACTIONS(15), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      sym__inline_space,
    STATE(16), 1,
      sym__block_comment,
    STATE(36), 1,
      sym_comment,
    STATE(50), 1,
      aux_sym__until_eol_repeat1,
    ACTIONS(150), 2,
      aux_sym__until_eol_token1,
      sym__line_comment,
  [841] = 4,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(154), 1,
      anon_sym_LPAREN,
    STATE(37), 1,
      sym_comment,
    ACTIONS(152), 4,
      anon_sym_COMMA,
      aux_sym__until_eol_token1,
      anon_sym_SLASH_STAR,
      sym__line_comment,
  [857] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(61), 1,
      aux_sym_directive_name_token1,
    ACTIONS(63), 1,
      aux_sym__displacement_expression_offset_token1,
    STATE(38), 1,
      sym_comment,
    STATE(91), 1,
      sym_symbol,
    STATE(95), 1,
      sym__displacement_expression_offset,
  [879] = 4,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(158), 1,
      anon_sym_COLON,
    STATE(39), 1,
      sym_comment,
    ACTIONS(156), 4,
      anon_sym_COMMA,
      aux_sym__until_eol_token1,
      anon_sym_SLASH_STAR,
      sym__line_comment,
  [895] = 5,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(136), 1,
      anon_sym_COMMA,
    STATE(31), 1,
      aux_sym_instruction_repeat1,
    STATE(40), 1,
      sym_comment,
    ACTIONS(160), 3,
      aux_sym__until_eol_token1,
      anon_sym_SLASH_STAR,
      sym__line_comment,
  [913] = 5,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(95), 1,
      anon_sym_COMMA,
    STATE(24), 1,
      aux_sym_directive_repeat1,
    STATE(41), 1,
      sym_comment,
    ACTIONS(162), 3,
      aux_sym__until_eol_token1,
      anon_sym_SLASH_STAR,
      sym__line_comment,
  [931] = 4,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(164), 1,
      anon_sym_LPAREN,
    STATE(42), 1,
      sym_comment,
    ACTIONS(156), 4,
      anon_sym_COMMA,
      aux_sym__until_eol_token1,
      anon_sym_SLASH_STAR,
      sym__line_comment,
  [947] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      sym__inline_space,
    ACTIONS(101), 1,
      aux_sym_comment_token1,
    ACTIONS(166), 1,
      aux_sym__until_eol_token1,
    ACTIONS(168), 1,
      anon_sym_STAR_SLASH,
    STATE(23), 1,
      aux_sym_comment_repeat1,
    STATE(43), 1,
      sym_comment,
  [969] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      sym__inline_space,
    ACTIONS(170), 1,
      aux_sym__until_eol_token1,
    ACTIONS(173), 1,
      aux_sym_comment_token1,
    ACTIONS(176), 1,
      anon_sym_STAR_SLASH,
    STATE(44), 2,
      sym_comment,
      aux_sym__block_comment_repeat1,
  [989] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      sym__inline_space,
    ACTIONS(128), 1,
      aux_sym__until_eol_token1,
    ACTIONS(130), 1,
      aux_sym_comment_token1,
    ACTIONS(178), 1,
      anon_sym_STAR_SLASH,
    STATE(44), 1,
      aux_sym__block_comment_repeat1,
    STATE(45), 1,
      sym_comment,
  [1011] = 4,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(182), 1,
      anon_sym_SQUOTE,
    STATE(46), 1,
      sym_comment,
    ACTIONS(180), 4,
      anon_sym_COMMA,
      aux_sym__until_eol_token1,
      anon_sym_SLASH_STAR,
      sym__line_comment,
  [1027] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(61), 1,
      aux_sym_directive_name_token1,
    ACTIONS(63), 1,
      aux_sym__displacement_expression_offset_token1,
    STATE(47), 1,
      sym_comment,
    STATE(91), 1,
      sym_symbol,
    STATE(99), 1,
      sym__displacement_expression_offset,
  [1049] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(61), 1,
      aux_sym_directive_name_token1,
    ACTIONS(63), 1,
      aux_sym__displacement_expression_offset_token1,
    STATE(48), 1,
      sym_comment,
    STATE(91), 1,
      sym_symbol,
    STATE(101), 1,
      sym__displacement_expression_offset,
  [1071] = 3,
    ACTIONS(17), 1,
      sym__inline_space,
    STATE(49), 1,
      sym_comment,
    ACTIONS(184), 4,
      anon_sym_COMMA,
      aux_sym__until_eol_token1,
      anon_sym_SLASH_STAR,
      sym__line_comment,
  [1084] = 4,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(188), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(186), 2,
      aux_sym__until_eol_token1,
      sym__line_comment,
    STATE(50), 2,
      sym_comment,
      aux_sym__until_eol_repeat1,
  [1099] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      sym__inline_space,
    ACTIONS(103), 1,
      anon_sym_STAR_SLASH,
    ACTIONS(191), 1,
      aux_sym_comment_token1,
    STATE(51), 1,
      sym_comment,
    STATE(64), 1,
      aux_sym_comment_repeat1,
  [1118] = 3,
    ACTIONS(17), 1,
      sym__inline_space,
    STATE(52), 1,
      sym_comment,
    ACTIONS(193), 4,
      anon_sym_COMMA,
      aux_sym__until_eol_token1,
      anon_sym_SLASH_STAR,
      sym__line_comment,
  [1131] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      sym__inline_space,
    ACTIONS(197), 1,
      aux_sym_string_token2,
    STATE(53), 1,
      sym_comment,
    ACTIONS(195), 2,
      anon_sym_DQUOTE,
      aux_sym_string_token1,
  [1148] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      sym__inline_space,
    ACTIONS(168), 1,
      anon_sym_STAR_SLASH,
    ACTIONS(191), 1,
      aux_sym_comment_token1,
    STATE(51), 1,
      aux_sym_comment_repeat1,
    STATE(54), 1,
      sym_comment,
  [1167] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      sym__inline_space,
    ACTIONS(191), 1,
      aux_sym_comment_token1,
    ACTIONS(199), 1,
      anon_sym_STAR_SLASH,
    STATE(55), 1,
      sym_comment,
    STATE(72), 1,
      aux_sym_comment_repeat1,
  [1186] = 3,
    ACTIONS(17), 1,
      sym__inline_space,
    STATE(56), 1,
      sym_comment,
    ACTIONS(201), 4,
      anon_sym_COMMA,
      aux_sym__until_eol_token1,
      anon_sym_SLASH_STAR,
      sym__line_comment,
  [1199] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      sym__inline_space,
    ACTIONS(205), 1,
      aux_sym_comment_token1,
    STATE(57), 1,
      sym_comment,
    ACTIONS(203), 2,
      aux_sym__until_eol_token1,
      anon_sym_STAR_SLASH,
  [1216] = 3,
    ACTIONS(17), 1,
      sym__inline_space,
    STATE(58), 1,
      sym_comment,
    ACTIONS(207), 4,
      anon_sym_COMMA,
      aux_sym__until_eol_token1,
      anon_sym_SLASH_STAR,
      sym__line_comment,
  [1229] = 3,
    ACTIONS(17), 1,
      sym__inline_space,
    STATE(59), 1,
      sym_comment,
    ACTIONS(152), 4,
      anon_sym_COMMA,
      aux_sym__until_eol_token1,
      anon_sym_SLASH_STAR,
      sym__line_comment,
  [1242] = 3,
    ACTIONS(17), 1,
      sym__inline_space,
    STATE(60), 1,
      sym_comment,
    ACTIONS(209), 4,
      anon_sym_COMMA,
      aux_sym__until_eol_token1,
      anon_sym_SLASH_STAR,
      sym__line_comment,
  [1255] = 3,
    ACTIONS(17), 1,
      sym__inline_space,
    STATE(61), 1,
      sym_comment,
    ACTIONS(211), 4,
      anon_sym_COMMA,
      aux_sym__until_eol_token1,
      anon_sym_SLASH_STAR,
      sym__line_comment,
  [1268] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      sym__inline_space,
    ACTIONS(215), 1,
      aux_sym_comment_token1,
    STATE(62), 1,
      sym_comment,
    ACTIONS(213), 2,
      aux_sym__until_eol_token1,
      anon_sym_STAR_SLASH,
  [1285] = 3,
    ACTIONS(17), 1,
      sym__inline_space,
    STATE(63), 1,
      sym_comment,
    ACTIONS(108), 4,
      anon_sym_COMMA,
      aux_sym__until_eol_token1,
      anon_sym_SLASH_STAR,
      sym__line_comment,
  [1298] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      sym__inline_space,
    ACTIONS(118), 1,
      anon_sym_STAR_SLASH,
    ACTIONS(217), 1,
      aux_sym_comment_token1,
    STATE(64), 2,
      sym_comment,
      aux_sym_comment_repeat1,
  [1315] = 3,
    ACTIONS(17), 1,
      sym__inline_space,
    STATE(65), 1,
      sym_comment,
    ACTIONS(220), 4,
      anon_sym_COMMA,
      aux_sym__until_eol_token1,
      anon_sym_SLASH_STAR,
      sym__line_comment,
  [1328] = 3,
    ACTIONS(17), 1,
      sym__inline_space,
    STATE(66), 1,
      sym_comment,
    ACTIONS(222), 4,
      anon_sym_COMMA,
      aux_sym__until_eol_token1,
      anon_sym_SLASH_STAR,
      sym__line_comment,
  [1341] = 3,
    ACTIONS(17), 1,
      sym__inline_space,
    STATE(67), 1,
      sym_comment,
    ACTIONS(224), 4,
      anon_sym_COMMA,
      aux_sym__until_eol_token1,
      anon_sym_SLASH_STAR,
      sym__line_comment,
  [1354] = 3,
    ACTIONS(17), 1,
      sym__inline_space,
    STATE(68), 1,
      sym_comment,
    ACTIONS(226), 4,
      anon_sym_COMMA,
      aux_sym__until_eol_token1,
      anon_sym_SLASH_STAR,
      sym__line_comment,
  [1367] = 3,
    ACTIONS(17), 1,
      sym__inline_space,
    STATE(69), 1,
      sym_comment,
    ACTIONS(228), 4,
      anon_sym_COMMA,
      aux_sym__until_eol_token1,
      anon_sym_SLASH_STAR,
      sym__line_comment,
  [1380] = 3,
    ACTIONS(17), 1,
      sym__inline_space,
    STATE(70), 1,
      sym_comment,
    ACTIONS(230), 4,
      anon_sym_COMMA,
      aux_sym__until_eol_token1,
      anon_sym_SLASH_STAR,
      sym__line_comment,
  [1393] = 3,
    ACTIONS(17), 1,
      sym__inline_space,
    STATE(71), 1,
      sym_comment,
    ACTIONS(232), 4,
      anon_sym_COMMA,
      aux_sym__until_eol_token1,
      anon_sym_SLASH_STAR,
      sym__line_comment,
  [1406] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      sym__inline_space,
    ACTIONS(191), 1,
      aux_sym_comment_token1,
    ACTIONS(234), 1,
      anon_sym_STAR_SLASH,
    STATE(64), 1,
      aux_sym_comment_repeat1,
    STATE(72), 1,
      sym_comment,
  [1425] = 3,
    ACTIONS(17), 1,
      sym__inline_space,
    STATE(73), 1,
      sym_comment,
    ACTIONS(126), 4,
      anon_sym_COMMA,
      aux_sym__until_eol_token1,
      anon_sym_SLASH_STAR,
      sym__line_comment,
  [1438] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(236), 1,
      anon_sym_COMMA,
    ACTIONS(238), 1,
      anon_sym_RPAREN,
    STATE(74), 1,
      sym_comment,
  [1454] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      sym__inline_space,
    STATE(75), 1,
      sym_comment,
    ACTIONS(134), 2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [1468] = 3,
    ACTIONS(17), 1,
      sym__inline_space,
    STATE(76), 1,
      sym_comment,
    ACTIONS(240), 3,
      aux_sym__until_eol_token1,
      anon_sym_SLASH_STAR,
      sym__line_comment,
  [1480] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(242), 1,
      anon_sym_COMMA,
    ACTIONS(244), 1,
      anon_sym_RPAREN,
    STATE(77), 1,
      sym_comment,
  [1496] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(246), 1,
      anon_sym_COMMA,
    ACTIONS(248), 1,
      anon_sym_RPAREN,
    STATE(78), 1,
      sym_comment,
  [1512] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(238), 1,
      anon_sym_RPAREN,
    ACTIONS(250), 1,
      anon_sym_COMMA,
    STATE(79), 1,
      sym_comment,
  [1528] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(246), 1,
      anon_sym_COMMA,
    ACTIONS(252), 1,
      sym_register,
    STATE(80), 1,
      sym_comment,
  [1544] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(254), 1,
      anon_sym_COMMA,
    ACTIONS(256), 1,
      sym_register,
    STATE(81), 1,
      sym_comment,
  [1560] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(236), 1,
      anon_sym_COMMA,
    ACTIONS(258), 1,
      sym_register,
    STATE(82), 1,
      sym_comment,
  [1576] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      sym__inline_space,
    STATE(83), 1,
      sym_comment,
    ACTIONS(154), 2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [1590] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      sym__inline_space,
    ACTIONS(260), 1,
      aux_sym_char_token1,
    ACTIONS(262), 1,
      aux_sym_char_token2,
    STATE(84), 1,
      sym_comment,
  [1606] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(244), 1,
      anon_sym_RPAREN,
    ACTIONS(264), 1,
      anon_sym_COMMA,
    STATE(85), 1,
      sym_comment,
  [1622] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(266), 1,
      anon_sym_COMMA,
    ACTIONS(268), 1,
      anon_sym_RPAREN,
    STATE(86), 1,
      sym_comment,
  [1638] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      sym__inline_space,
    ACTIONS(203), 1,
      anon_sym_STAR_SLASH,
    ACTIONS(205), 1,
      aux_sym_comment_token1,
    STATE(87), 1,
      sym_comment,
  [1654] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(268), 1,
      anon_sym_RPAREN,
    ACTIONS(270), 1,
      anon_sym_COMMA,
    STATE(88), 1,
      sym_comment,
  [1670] = 3,
    ACTIONS(17), 1,
      sym__inline_space,
    STATE(89), 1,
      sym_comment,
    ACTIONS(272), 3,
      aux_sym__until_eol_token1,
      anon_sym_SLASH_STAR,
      sym__line_comment,
  [1682] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(274), 1,
      anon_sym_COMMA,
    ACTIONS(276), 1,
      anon_sym_RPAREN,
    STATE(90), 1,
      sym_comment,
  [1698] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      sym__inline_space,
    STATE(91), 1,
      sym_comment,
    ACTIONS(164), 2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [1712] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(278), 1,
      anon_sym_COMMA,
    ACTIONS(280), 1,
      anon_sym_RPAREN,
    STATE(92), 1,
      sym_comment,
  [1728] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(242), 1,
      anon_sym_COMMA,
    ACTIONS(282), 1,
      sym_register,
    STATE(93), 1,
      sym_comment,
  [1744] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(284), 1,
      aux_sym_directive_name_token1,
    STATE(94), 1,
      sym_comment,
  [1757] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(276), 1,
      anon_sym_RPAREN,
    STATE(95), 1,
      sym_comment,
  [1770] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(286), 1,
      ts_builtin_sym_end,
    STATE(96), 1,
      sym_comment,
  [1783] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(280), 1,
      anon_sym_RPAREN,
    STATE(97), 1,
      sym_comment,
  [1796] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(244), 1,
      anon_sym_RPAREN,
    STATE(98), 1,
      sym_comment,
  [1809] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(288), 1,
      anon_sym_RPAREN,
    STATE(99), 1,
      sym_comment,
  [1822] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(290), 1,
      anon_sym_LPAREN,
    STATE(100), 1,
      sym_comment,
  [1835] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(292), 1,
      anon_sym_RPAREN,
    STATE(101), 1,
      sym_comment,
  [1848] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(268), 1,
      anon_sym_RPAREN,
    STATE(102), 1,
      sym_comment,
  [1861] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(238), 1,
      anon_sym_RPAREN,
    STATE(103), 1,
      sym_comment,
  [1874] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      sym__inline_space,
    ACTIONS(294), 1,
      anon_sym_LPAREN,
    STATE(104), 1,
      sym_comment,
  [1887] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(296), 1,
      sym__inline_space,
    STATE(105), 1,
      sym_comment,
  [1897] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(298), 1,
      sym__inline_space,
    STATE(106), 1,
      sym_comment,
  [1907] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(300), 1,
      sym__inline_space,
    STATE(107), 1,
      sym_comment,
  [1917] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(302), 1,
      sym__inline_space,
    STATE(108), 1,
      sym_comment,
  [1927] = 1,
    ACTIONS(272), 1,
      ts_builtin_sym_end,
  [1931] = 1,
    ACTIONS(240), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 48,
  [SMALL_STATE(4)] = 96,
  [SMALL_STATE(5)] = 136,
  [SMALL_STATE(6)] = 178,
  [SMALL_STATE(7)] = 210,
  [SMALL_STATE(8)] = 242,
  [SMALL_STATE(9)] = 269,
  [SMALL_STATE(10)] = 290,
  [SMALL_STATE(11)] = 315,
  [SMALL_STATE(12)] = 340,
  [SMALL_STATE(13)] = 365,
  [SMALL_STATE(14)] = 390,
  [SMALL_STATE(15)] = 407,
  [SMALL_STATE(16)] = 424,
  [SMALL_STATE(17)] = 441,
  [SMALL_STATE(18)] = 466,
  [SMALL_STATE(19)] = 483,
  [SMALL_STATE(20)] = 508,
  [SMALL_STATE(21)] = 525,
  [SMALL_STATE(22)] = 547,
  [SMALL_STATE(23)] = 565,
  [SMALL_STATE(24)] = 587,
  [SMALL_STATE(25)] = 603,
  [SMALL_STATE(26)] = 623,
  [SMALL_STATE(27)] = 641,
  [SMALL_STATE(28)] = 657,
  [SMALL_STATE(29)] = 679,
  [SMALL_STATE(30)] = 701,
  [SMALL_STATE(31)] = 715,
  [SMALL_STATE(32)] = 733,
  [SMALL_STATE(33)] = 755,
  [SMALL_STATE(34)] = 777,
  [SMALL_STATE(35)] = 799,
  [SMALL_STATE(36)] = 821,
  [SMALL_STATE(37)] = 841,
  [SMALL_STATE(38)] = 857,
  [SMALL_STATE(39)] = 879,
  [SMALL_STATE(40)] = 895,
  [SMALL_STATE(41)] = 913,
  [SMALL_STATE(42)] = 931,
  [SMALL_STATE(43)] = 947,
  [SMALL_STATE(44)] = 969,
  [SMALL_STATE(45)] = 989,
  [SMALL_STATE(46)] = 1011,
  [SMALL_STATE(47)] = 1027,
  [SMALL_STATE(48)] = 1049,
  [SMALL_STATE(49)] = 1071,
  [SMALL_STATE(50)] = 1084,
  [SMALL_STATE(51)] = 1099,
  [SMALL_STATE(52)] = 1118,
  [SMALL_STATE(53)] = 1131,
  [SMALL_STATE(54)] = 1148,
  [SMALL_STATE(55)] = 1167,
  [SMALL_STATE(56)] = 1186,
  [SMALL_STATE(57)] = 1199,
  [SMALL_STATE(58)] = 1216,
  [SMALL_STATE(59)] = 1229,
  [SMALL_STATE(60)] = 1242,
  [SMALL_STATE(61)] = 1255,
  [SMALL_STATE(62)] = 1268,
  [SMALL_STATE(63)] = 1285,
  [SMALL_STATE(64)] = 1298,
  [SMALL_STATE(65)] = 1315,
  [SMALL_STATE(66)] = 1328,
  [SMALL_STATE(67)] = 1341,
  [SMALL_STATE(68)] = 1354,
  [SMALL_STATE(69)] = 1367,
  [SMALL_STATE(70)] = 1380,
  [SMALL_STATE(71)] = 1393,
  [SMALL_STATE(72)] = 1406,
  [SMALL_STATE(73)] = 1425,
  [SMALL_STATE(74)] = 1438,
  [SMALL_STATE(75)] = 1454,
  [SMALL_STATE(76)] = 1468,
  [SMALL_STATE(77)] = 1480,
  [SMALL_STATE(78)] = 1496,
  [SMALL_STATE(79)] = 1512,
  [SMALL_STATE(80)] = 1528,
  [SMALL_STATE(81)] = 1544,
  [SMALL_STATE(82)] = 1560,
  [SMALL_STATE(83)] = 1576,
  [SMALL_STATE(84)] = 1590,
  [SMALL_STATE(85)] = 1606,
  [SMALL_STATE(86)] = 1622,
  [SMALL_STATE(87)] = 1638,
  [SMALL_STATE(88)] = 1654,
  [SMALL_STATE(89)] = 1670,
  [SMALL_STATE(90)] = 1682,
  [SMALL_STATE(91)] = 1698,
  [SMALL_STATE(92)] = 1712,
  [SMALL_STATE(93)] = 1728,
  [SMALL_STATE(94)] = 1744,
  [SMALL_STATE(95)] = 1757,
  [SMALL_STATE(96)] = 1770,
  [SMALL_STATE(97)] = 1783,
  [SMALL_STATE(98)] = 1796,
  [SMALL_STATE(99)] = 1809,
  [SMALL_STATE(100)] = 1822,
  [SMALL_STATE(101)] = 1835,
  [SMALL_STATE(102)] = 1848,
  [SMALL_STATE(103)] = 1861,
  [SMALL_STATE(104)] = 1874,
  [SMALL_STATE(105)] = 1887,
  [SMALL_STATE(106)] = 1897,
  [SMALL_STATE(107)] = 1907,
  [SMALL_STATE(108)] = 1917,
  [SMALL_STATE(109)] = 1927,
  [SMALL_STATE(110)] = 1931,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(106),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(94),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(106),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(4),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(43),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__block_comment, 3),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__block_comment, 3),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__block_comment, 5),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__block_comment, 5),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__until_eol, 2),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__until_eol, 2),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__block_comment, 4),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__block_comment, 4),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 3),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [105] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_directive_repeat1, 2), SHIFT_REPEAT(6),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_directive_repeat1, 2),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2),
  [112] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(53),
  [115] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(53),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_comment_repeat1, 2),
  [120] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2), SHIFT_REPEAT(57),
  [123] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_instruction_repeat1, 2), SHIFT_REPEAT(3),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_instruction_repeat1, 2),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [130] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbol, 1),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 4),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [144] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__displacement_expression_offset, 1, .production_id = 1),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__operand, 1),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 3),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 4),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__displacement_expression_offset, 1),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [170] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__block_comment_repeat1, 2), SHIFT_REPEAT(62),
  [173] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__block_comment_repeat1, 2), SHIFT_REPEAT(62),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__block_comment_repeat1, 2),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_char, 2),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constant, 2),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__until_eol_repeat1, 2),
  [188] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__until_eol_repeat1, 2), SHIFT_REPEAT(54),
  [191] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 1),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 1),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive_arg, 1),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_comment_repeat1, 1),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 1),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__displacement_expression, 10),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_char, 3),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__block_comment_repeat1, 1),
  [215] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__block_comment_repeat1, 1),
  [217] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2), SHIFT_REPEAT(87),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__displacement_expression, 9),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__displacement_expression, 8),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__displacement_expression, 7),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__displacement_expression, 6),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__displacement_expression, 5),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__displacement_expression, 3),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__displacement_expression, 4),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [262] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [286] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [298] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction_name, 1),
  [300] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive_name, 2),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_YOUR_LANGUAGE_NAME(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
