#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 129
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 58
#define ALIAS_COUNT 1
#define TOKEN_COUNT 31
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 10
#define PRODUCTION_ID_COUNT 3

enum {
  sym_label = 1,
  anon_sym_COMMA = 2,
  sym_directive_name = 3,
  anon_sym_AT = 4,
  anon_sym_EQ = 5,
  anon_sym_DASH = 6,
  anon_sym_PLUS = 7,
  anon_sym_STAR = 8,
  anon_sym_SLASH = 9,
  anon_sym_LPAREN = 10,
  anon_sym_RPAREN = 11,
  aux_sym__operand_symbol_token1 = 12,
  anon_sym_COLON = 13,
  anon_sym_DOLLAR = 14,
  anon_sym_SQUOTE = 15,
  aux_sym_char_token1 = 16,
  sym__character_escapes = 17,
  anon_sym_DQUOTE = 18,
  aux_sym_string_token1 = 19,
  sym__string_escapes = 20,
  sym__integer = 21,
  sym__float = 22,
  sym__identifier = 23,
  sym_register = 24,
  aux_sym_comment_token1 = 25,
  anon_sym_SLASH_STAR = 26,
  aux_sym_comment_token2 = 27,
  anon_sym_STAR_SLASH = 28,
  sym__inline_space = 29,
  sym__eol = 30,
  sym_source_file = 31,
  sym__statement = 32,
  sym_directive = 33,
  sym__directive_arg = 34,
  sym_type = 35,
  sym_assignment = 36,
  sym_expression = 37,
  sym__paren_expression = 38,
  sym__sub_expression = 39,
  sym_instruction = 40,
  sym__operand = 41,
  sym__operand_symbol = 42,
  sym__displacement_expression = 43,
  sym__displacement_expression_offset = 44,
  sym_constant = 45,
  sym_char = 46,
  sym_string = 47,
  sym_number = 48,
  sym_symbol = 49,
  sym_comment = 50,
  aux_sym_source_file_repeat1 = 51,
  aux_sym_directive_repeat1 = 52,
  aux_sym_assignment_repeat1 = 53,
  aux_sym_expression_repeat1 = 54,
  aux_sym_instruction_repeat1 = 55,
  aux_sym_string_repeat1 = 56,
  aux_sym_comment_repeat1 = 57,
  alias_sym_instruction_name = 58,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_label] = "label",
  [anon_sym_COMMA] = ",",
  [sym_directive_name] = "directive_name",
  [anon_sym_AT] = "@",
  [anon_sym_EQ] = "=",
  [anon_sym_DASH] = "-",
  [anon_sym_PLUS] = "+",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [aux_sym__operand_symbol_token1] = "symbol",
  [anon_sym_COLON] = ":",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_char_token1] = "char_token1",
  [sym__character_escapes] = "_character_escapes",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [sym__string_escapes] = "_string_escapes",
  [sym__integer] = "_integer",
  [sym__float] = "_float",
  [sym__identifier] = "_identifier",
  [sym_register] = "register",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_SLASH_STAR] = "/*",
  [aux_sym_comment_token2] = "comment_token2",
  [anon_sym_STAR_SLASH] = "*/",
  [sym__inline_space] = "_inline_space",
  [sym__eol] = "_eol",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_directive] = "directive",
  [sym__directive_arg] = "_directive_arg",
  [sym_type] = "type",
  [sym_assignment] = "assignment",
  [sym_expression] = "expression",
  [sym__paren_expression] = "_paren_expression",
  [sym__sub_expression] = "_sub_expression",
  [sym_instruction] = "instruction",
  [sym__operand] = "_operand",
  [sym__operand_symbol] = "_operand_symbol",
  [sym__displacement_expression] = "_displacement_expression",
  [sym__displacement_expression_offset] = "_displacement_expression_offset",
  [sym_constant] = "constant",
  [sym_char] = "char",
  [sym_string] = "string",
  [sym_number] = "number",
  [sym_symbol] = "symbol",
  [sym_comment] = "comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_directive_repeat1] = "directive_repeat1",
  [aux_sym_assignment_repeat1] = "assignment_repeat1",
  [aux_sym_expression_repeat1] = "expression_repeat1",
  [aux_sym_instruction_repeat1] = "instruction_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_comment_repeat1] = "comment_repeat1",
  [alias_sym_instruction_name] = "instruction_name",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_label] = sym_label,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_directive_name] = sym_directive_name,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [aux_sym__operand_symbol_token1] = sym_symbol,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_char_token1] = aux_sym_char_token1,
  [sym__character_escapes] = sym__character_escapes,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym__string_escapes] = sym__string_escapes,
  [sym__integer] = sym__integer,
  [sym__float] = sym__float,
  [sym__identifier] = sym__identifier,
  [sym_register] = sym_register,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_SLASH_STAR] = anon_sym_SLASH_STAR,
  [aux_sym_comment_token2] = aux_sym_comment_token2,
  [anon_sym_STAR_SLASH] = anon_sym_STAR_SLASH,
  [sym__inline_space] = sym__inline_space,
  [sym__eol] = sym__eol,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_directive] = sym_directive,
  [sym__directive_arg] = sym__directive_arg,
  [sym_type] = sym_type,
  [sym_assignment] = sym_assignment,
  [sym_expression] = sym_expression,
  [sym__paren_expression] = sym__paren_expression,
  [sym__sub_expression] = sym__sub_expression,
  [sym_instruction] = sym_instruction,
  [sym__operand] = sym__operand,
  [sym__operand_symbol] = sym__operand_symbol,
  [sym__displacement_expression] = sym__displacement_expression,
  [sym__displacement_expression_offset] = sym__displacement_expression_offset,
  [sym_constant] = sym_constant,
  [sym_char] = sym_char,
  [sym_string] = sym_string,
  [sym_number] = sym_number,
  [sym_symbol] = sym_symbol,
  [sym_comment] = sym_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_directive_repeat1] = aux_sym_directive_repeat1,
  [aux_sym_assignment_repeat1] = aux_sym_assignment_repeat1,
  [aux_sym_expression_repeat1] = aux_sym_expression_repeat1,
  [aux_sym_instruction_repeat1] = aux_sym_instruction_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_comment_repeat1] = aux_sym_comment_repeat1,
  [alias_sym_instruction_name] = alias_sym_instruction_name,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_label] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_directive_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__operand_symbol_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_char_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__character_escapes] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__string_escapes] = {
    .visible = false,
    .named = true,
  },
  [sym__integer] = {
    .visible = false,
    .named = true,
  },
  [sym__float] = {
    .visible = false,
    .named = true,
  },
  [sym__identifier] = {
    .visible = false,
    .named = true,
  },
  [sym_register] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_STAR_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym__inline_space] = {
    .visible = false,
    .named = true,
  },
  [sym__eol] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym__directive_arg] = {
    .visible = false,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__paren_expression] = {
    .visible = false,
    .named = true,
  },
  [sym__sub_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym__operand] = {
    .visible = false,
    .named = true,
  },
  [sym__operand_symbol] = {
    .visible = false,
    .named = true,
  },
  [sym__displacement_expression] = {
    .visible = false,
    .named = true,
  },
  [sym__displacement_expression_offset] = {
    .visible = false,
    .named = true,
  },
  [sym_constant] = {
    .visible = true,
    .named = true,
  },
  [sym_char] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_directive_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_assignment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_instruction_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_instruction_name] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = alias_sym_instruction_name,
  },
  [2] = {
    [0] = sym_number,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym_symbol, 2,
    sym_symbol,
    alias_sym_instruction_name,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 41,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 39,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 17,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 122,
  [127] = 123,
  [128] = 120,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(20);
      if (lookahead == '\n') ADVANCE(36);
      if (lookahead == '\r') ADVANCE(36);
      if (lookahead == '"') ADVANCE(41);
      if (lookahead == '#') ADVANCE(39);
      if (lookahead == '$') ADVANCE(34);
      if (lookahead == '\'') ADVANCE(35);
      if (lookahead == '(') ADVANCE(30);
      if (lookahead == ')') ADVANCE(31);
      if (lookahead == '*') ADVANCE(28);
      if (lookahead == '+') ADVANCE(27);
      if (lookahead == ',') ADVANCE(22);
      if (lookahead == '-') ADVANCE(26);
      if (lookahead == '/') ADVANCE(29);
      if (lookahead == ':') ADVANCE(33);
      if (lookahead == '=') ADVANCE(25);
      if (lookahead == '@') ADVANCE(24);
      if (lookahead == '\\') ADVANCE(69);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(78);
      if (lookahead == '\r') ADVANCE(70);
      if (lookahead == '#') ADVANCE(67);
      if (lookahead == '*') ADVANCE(72);
      if (lookahead == '/') ADVANCE(71);
      if (lookahead == ';') ADVANCE(69);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(73);
      if (lookahead != 0) ADVANCE(69);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(41);
      if (lookahead == '#') ADVANCE(67);
      if (lookahead == '$') ADVANCE(34);
      if (lookahead == '%') ADVANCE(17);
      if (lookahead == '\'') ADVANCE(35);
      if (lookahead == '(') ADVANCE(30);
      if (lookahead == '*') ADVANCE(28);
      if (lookahead == '-') ADVANCE(7);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '0') ADVANCE(51);
      if (lookahead == '=') ADVANCE(25);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(75);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(41);
      if (lookahead == '#') ADVANCE(45);
      if (lookahead == '/') ADVANCE(43);
      if (lookahead == '\\') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(42);
      END_STATE();
    case 4:
      if (lookahead == '#') ADVANCE(39);
      if (lookahead == '/') ADVANCE(37);
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(36);
      END_STATE();
    case 5:
      if (lookahead == '#') ADVANCE(67);
      if (lookahead == '%') ADVANCE(17);
      if (lookahead == '(') ADVANCE(30);
      if (lookahead == '-') ADVANCE(7);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '0') ADVANCE(52);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(75);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(68);
      END_STATE();
    case 7:
      if (lookahead == '0') ADVANCE(52);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(55);
      END_STATE();
    case 8:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(62);
      END_STATE();
    case 9:
      if (lookahead == '"' ||
          lookahead == '\\' ||
          lookahead == 'b' ||
          lookahead == 'f' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(46);
      if (lookahead == 'x') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 10:
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '\\' ||
          lookahead == 'b' ||
          lookahead == 'f' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(40);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(62);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(57);
      END_STATE();
    case 15:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(46);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(15);
      END_STATE();
    case 17:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 18:
      if (eof) ADVANCE(20);
      if (lookahead == '\n') ADVANCE(78);
      if (lookahead == '\r') ADVANCE(77);
      if (lookahead == '"') ADVANCE(41);
      if (lookahead == '#') ADVANCE(67);
      if (lookahead == '\'') ADVANCE(35);
      if (lookahead == '(') ADVANCE(30);
      if (lookahead == ',') ADVANCE(22);
      if (lookahead == '-') ADVANCE(7);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '0') ADVANCE(51);
      if (lookahead == ';') ADVANCE(76);
      if (lookahead == '@') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(75);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 19:
      if (eof) ADVANCE(20);
      if (lookahead == '\n') ADVANCE(78);
      if (lookahead == '\r') ADVANCE(77);
      if (lookahead == '#') ADVANCE(67);
      if (lookahead == '%') ADVANCE(17);
      if (lookahead == '\'') ADVANCE(35);
      if (lookahead == '(') ADVANCE(30);
      if (lookahead == ')') ADVANCE(31);
      if (lookahead == '*') ADVANCE(28);
      if (lookahead == '+') ADVANCE(27);
      if (lookahead == ',') ADVANCE(22);
      if (lookahead == '-') ADVANCE(26);
      if (lookahead == '.') ADVANCE(63);
      if (lookahead == '/') ADVANCE(29);
      if (lookahead == ':') ADVANCE(33);
      if (lookahead == ';') ADVANCE(76);
      if (lookahead == '=') ADVANCE(25);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(75);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_label);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_directive_name);
      if (lookahead == ':') ADVANCE(21);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(68);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym__operand_symbol_token1);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_char_token1);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_char_token1);
      if (lookahead == '*') ADVANCE(68);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_char_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(75);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_char_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(67);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym__character_escapes);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '*') ADVANCE(68);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(75);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(67);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym__string_escapes);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym__integer);
      if (lookahead == '.') ADVANCE(61);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(60);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(8);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(48);
      if (('2' <= lookahead && lookahead <= '9')) ADVANCE(60);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym__integer);
      if (lookahead == '.') ADVANCE(61);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(8);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(48);
      if (('2' <= lookahead && lookahead <= '9')) ADVANCE(60);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym__integer);
      if (lookahead == '.') ADVANCE(61);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(50);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym__integer);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(57);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym__integer);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(47);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(54);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym__integer);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(53);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(54);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym__integer);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(53);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym__integer);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym__integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym__integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(57);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym__integer);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym__float);
      if (lookahead == '.') ADVANCE(61);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(60);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(60);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym__float);
      if (lookahead == '.') ADVANCE(61);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(60);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(50);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym__float);
      if (lookahead == '.') ADVANCE(61);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym__float);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym__float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == ':') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(64);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == ':') ADVANCE(21);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_register);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == '\n') ADVANCE(76);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == '*') ADVANCE(68);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == '/') ADVANCE(74);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(75);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_STAR_SLASH);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym__inline_space);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(75);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym__eol);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym__eol);
      if (lookahead == '\n') ADVANCE(76);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym__eol);
      if (lookahead == '\r') ADVANCE(76);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 19},
  [2] = {.lex_state = 18},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 18},
  [7] = {.lex_state = 19},
  [8] = {.lex_state = 19},
  [9] = {.lex_state = 19},
  [10] = {.lex_state = 19},
  [11] = {.lex_state = 19},
  [12] = {.lex_state = 18},
  [13] = {.lex_state = 19},
  [14] = {.lex_state = 19},
  [15] = {.lex_state = 18},
  [16] = {.lex_state = 19},
  [17] = {.lex_state = 19},
  [18] = {.lex_state = 18},
  [19] = {.lex_state = 19},
  [20] = {.lex_state = 19},
  [21] = {.lex_state = 19},
  [22] = {.lex_state = 19},
  [23] = {.lex_state = 18},
  [24] = {.lex_state = 19},
  [25] = {.lex_state = 18},
  [26] = {.lex_state = 19},
  [27] = {.lex_state = 5},
  [28] = {.lex_state = 19},
  [29] = {.lex_state = 5},
  [30] = {.lex_state = 5},
  [31] = {.lex_state = 19},
  [32] = {.lex_state = 5},
  [33] = {.lex_state = 19},
  [34] = {.lex_state = 5},
  [35] = {.lex_state = 19},
  [36] = {.lex_state = 5},
  [37] = {.lex_state = 3},
  [38] = {.lex_state = 19},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 19},
  [44] = {.lex_state = 5},
  [45] = {.lex_state = 5},
  [46] = {.lex_state = 5},
  [47] = {.lex_state = 19},
  [48] = {.lex_state = 19},
  [49] = {.lex_state = 19},
  [50] = {.lex_state = 19},
  [51] = {.lex_state = 5},
  [52] = {.lex_state = 5},
  [53] = {.lex_state = 19},
  [54] = {.lex_state = 19},
  [55] = {.lex_state = 19},
  [56] = {.lex_state = 19},
  [57] = {.lex_state = 19},
  [58] = {.lex_state = 19},
  [59] = {.lex_state = 3},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 3},
  [62] = {.lex_state = 19},
  [63] = {.lex_state = 19},
  [64] = {.lex_state = 19},
  [65] = {.lex_state = 19},
  [66] = {.lex_state = 19},
  [67] = {.lex_state = 19},
  [68] = {.lex_state = 19},
  [69] = {.lex_state = 3},
  [70] = {.lex_state = 19},
  [71] = {.lex_state = 19},
  [72] = {.lex_state = 19},
  [73] = {.lex_state = 19},
  [74] = {.lex_state = 19},
  [75] = {.lex_state = 19},
  [76] = {.lex_state = 19},
  [77] = {.lex_state = 19},
  [78] = {.lex_state = 19},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 19},
  [81] = {.lex_state = 19},
  [82] = {.lex_state = 19},
  [83] = {.lex_state = 19},
  [84] = {.lex_state = 19},
  [85] = {.lex_state = 19},
  [86] = {.lex_state = 19},
  [87] = {.lex_state = 19},
  [88] = {.lex_state = 19},
  [89] = {.lex_state = 4},
  [90] = {.lex_state = 19},
  [91] = {.lex_state = 19},
  [92] = {.lex_state = 19},
  [93] = {.lex_state = 19},
  [94] = {.lex_state = 19},
  [95] = {.lex_state = 19},
  [96] = {.lex_state = 19},
  [97] = {.lex_state = 19},
  [98] = {.lex_state = 19},
  [99] = {.lex_state = 19},
  [100] = {.lex_state = 19},
  [101] = {.lex_state = 19},
  [102] = {.lex_state = 19},
  [103] = {.lex_state = 19},
  [104] = {.lex_state = 19},
  [105] = {.lex_state = 19},
  [106] = {.lex_state = 19},
  [107] = {.lex_state = 19},
  [108] = {.lex_state = 19},
  [109] = {.lex_state = 19},
  [110] = {.lex_state = 19},
  [111] = {.lex_state = 19},
  [112] = {.lex_state = 19},
  [113] = {.lex_state = 19},
  [114] = {.lex_state = 19},
  [115] = {.lex_state = 19},
  [116] = {.lex_state = 19},
  [117] = {.lex_state = 19},
  [118] = {.lex_state = 19},
  [119] = {.lex_state = 19},
  [120] = {.lex_state = 19},
  [121] = {.lex_state = 19},
  [122] = {.lex_state = 19},
  [123] = {.lex_state = 19},
  [124] = {.lex_state = 19},
  [125] = {.lex_state = 18},
  [126] = {(TSStateId)(-1)},
  [127] = {(TSStateId)(-1)},
  [128] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [aux_sym__operand_symbol_token1] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [aux_sym_char_token1] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [aux_sym_string_token1] = ACTIONS(1),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [aux_sym_comment_token2] = ACTIONS(1),
    [sym__inline_space] = ACTIONS(7),
  },
  [1] = {
    [sym_source_file] = STATE(114),
    [sym__statement] = STATE(90),
    [sym_directive] = STATE(85),
    [sym_assignment] = STATE(85),
    [sym_instruction] = STATE(85),
    [sym_symbol] = STATE(57),
    [sym_comment] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(9),
    [sym_label] = ACTIONS(11),
    [sym_directive_name] = ACTIONS(13),
    [sym__identifier] = ACTIONS(15),
    [aux_sym_comment_token1] = ACTIONS(17),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [sym__inline_space] = ACTIONS(19),
    [sym__eol] = ACTIONS(21),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 16,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(25), 1,
      anon_sym_AT,
    ACTIONS(27), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_SQUOTE,
    ACTIONS(31), 1,
      anon_sym_DQUOTE,
    ACTIONS(35), 1,
      sym__identifier,
    STATE(2), 1,
      sym_comment,
    STATE(14), 1,
      sym__paren_expression,
    STATE(26), 1,
      sym__sub_expression,
    STATE(82), 1,
      sym__directive_arg,
    ACTIONS(33), 2,
      sym__integer,
      sym__float,
    STATE(22), 2,
      sym_number,
      sym_symbol,
    ACTIONS(23), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      sym__eol,
    STATE(65), 4,
      sym_type,
      sym_expression,
      sym_char,
      sym_string,
  [56] = 15,
    ACTIONS(29), 1,
      anon_sym_SQUOTE,
    ACTIONS(31), 1,
      anon_sym_DQUOTE,
    ACTIONS(33), 1,
      sym__float,
    ACTIONS(39), 1,
      anon_sym_STAR,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      aux_sym__operand_symbol_token1,
    ACTIONS(45), 1,
      anon_sym_DOLLAR,
    ACTIONS(47), 1,
      sym__integer,
    ACTIONS(49), 1,
      sym_register,
    STATE(3), 1,
      sym_comment,
    STATE(49), 1,
      sym__operand,
    STATE(50), 1,
      sym__operand_symbol,
    STATE(111), 1,
      sym__displacement_expression_offset,
    ACTIONS(37), 4,
      anon_sym_EQ,
      aux_sym_comment_token1,
      anon_sym_SLASH_STAR,
      sym__inline_space,
    STATE(72), 5,
      sym__displacement_expression,
      sym_constant,
      sym_char,
      sym_string,
      sym_number,
  [109] = 16,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(29), 1,
      anon_sym_SQUOTE,
    ACTIONS(31), 1,
      anon_sym_DQUOTE,
    ACTIONS(33), 1,
      sym__float,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      aux_sym__operand_symbol_token1,
    ACTIONS(45), 1,
      anon_sym_DOLLAR,
    ACTIONS(47), 1,
      sym__integer,
    ACTIONS(49), 1,
      sym_register,
    STATE(4), 1,
      sym_comment,
    STATE(50), 1,
      sym__operand_symbol,
    STATE(78), 1,
      sym__operand,
    STATE(111), 1,
      sym__displacement_expression_offset,
    STATE(72), 5,
      sym__displacement_expression,
      sym_constant,
      sym_char,
      sym_string,
      sym_number,
  [162] = 16,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(29), 1,
      anon_sym_SQUOTE,
    ACTIONS(31), 1,
      anon_sym_DQUOTE,
    ACTIONS(33), 1,
      sym__float,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      aux_sym__operand_symbol_token1,
    ACTIONS(45), 1,
      anon_sym_DOLLAR,
    ACTIONS(47), 1,
      sym__integer,
    ACTIONS(49), 1,
      sym_register,
    STATE(5), 1,
      sym_comment,
    STATE(50), 1,
      sym__operand_symbol,
    STATE(55), 1,
      sym__operand,
    STATE(111), 1,
      sym__displacement_expression_offset,
    STATE(72), 5,
      sym__displacement_expression,
      sym_constant,
      sym_char,
      sym_string,
      sym_number,
  [215] = 15,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(25), 1,
      anon_sym_AT,
    ACTIONS(27), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_SQUOTE,
    ACTIONS(31), 1,
      anon_sym_DQUOTE,
    ACTIONS(35), 1,
      sym__identifier,
    STATE(6), 1,
      sym_comment,
    STATE(14), 1,
      sym__paren_expression,
    STATE(26), 1,
      sym__sub_expression,
    STATE(43), 1,
      sym__directive_arg,
    ACTIONS(33), 2,
      sym__integer,
      sym__float,
    STATE(22), 2,
      sym_number,
      sym_symbol,
    STATE(65), 4,
      sym_type,
      sym_expression,
      sym_char,
      sym_string,
  [266] = 12,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    ACTIONS(53), 1,
      sym_label,
    ACTIONS(56), 1,
      sym_directive_name,
    ACTIONS(59), 1,
      sym__identifier,
    ACTIONS(62), 1,
      sym__eol,
    STATE(57), 1,
      sym_symbol,
    STATE(116), 1,
      sym__statement,
    STATE(7), 2,
      sym_comment,
      aux_sym_source_file_repeat1,
    STATE(85), 3,
      sym_directive,
      sym_assignment,
      sym_instruction,
  [306] = 13,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(13), 1,
      sym_directive_name,
    ACTIONS(15), 1,
      sym__identifier,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(21), 1,
      sym__eol,
    ACTIONS(65), 1,
      ts_builtin_sym_end,
    ACTIONS(67), 1,
      sym_label,
    STATE(7), 1,
      aux_sym_source_file_repeat1,
    STATE(8), 1,
      sym_comment,
    STATE(57), 1,
      sym_symbol,
    STATE(92), 1,
      sym__statement,
    STATE(85), 3,
      sym_directive,
      sym_assignment,
      sym_instruction,
  [348] = 7,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(74), 1,
      anon_sym_SLASH,
    STATE(9), 2,
      sym_comment,
      aux_sym_expression_repeat1,
    ACTIONS(69), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym__eol,
    ACTIONS(71), 4,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
  [377] = 8,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(81), 1,
      anon_sym_SLASH,
    STATE(9), 1,
      aux_sym_expression_repeat1,
    STATE(10), 1,
      sym_comment,
    ACTIONS(77), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym__eol,
    ACTIONS(79), 4,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
  [408] = 11,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(15), 1,
      sym__identifier,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(65), 1,
      ts_builtin_sym_end,
    ACTIONS(83), 1,
      sym_directive_name,
    ACTIONS(85), 1,
      sym__eol,
    STATE(11), 1,
      sym_comment,
    STATE(57), 1,
      sym_symbol,
    STATE(102), 1,
      sym__statement,
    STATE(85), 3,
      sym_directive,
      sym_assignment,
      sym_instruction,
  [444] = 11,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(27), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 1,
      sym__identifier,
    STATE(12), 1,
      sym_comment,
    STATE(14), 1,
      sym__paren_expression,
    STATE(26), 1,
      sym__sub_expression,
    STATE(121), 1,
      sym_expression,
    ACTIONS(33), 2,
      sym__integer,
      sym__float,
    STATE(19), 2,
      sym_number,
      sym_symbol,
  [480] = 6,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(89), 1,
      anon_sym_SLASH,
    STATE(13), 1,
      sym_comment,
    ACTIONS(87), 8,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_RPAREN,
      sym__eol,
  [506] = 7,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(95), 1,
      anon_sym_SLASH,
    STATE(14), 1,
      sym_comment,
    ACTIONS(91), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym__eol,
    ACTIONS(93), 4,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
  [534] = 11,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(27), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 1,
      sym__identifier,
    STATE(14), 1,
      sym__paren_expression,
    STATE(15), 1,
      sym_comment,
    STATE(26), 1,
      sym__sub_expression,
    STATE(104), 1,
      sym_expression,
    ACTIONS(33), 2,
      sym__integer,
      sym__float,
    STATE(19), 2,
      sym_number,
      sym_symbol,
  [570] = 6,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(99), 1,
      anon_sym_SLASH,
    STATE(16), 1,
      sym_comment,
    ACTIONS(97), 8,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_RPAREN,
      sym__eol,
  [596] = 6,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(103), 1,
      anon_sym_SLASH,
    STATE(17), 1,
      sym_comment,
    ACTIONS(101), 8,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_RPAREN,
      sym__eol,
  [622] = 11,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(27), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 1,
      sym__identifier,
    STATE(14), 1,
      sym__paren_expression,
    STATE(18), 1,
      sym_comment,
    STATE(26), 1,
      sym__sub_expression,
    STATE(93), 1,
      sym_expression,
    ACTIONS(33), 2,
      sym__integer,
      sym__float,
    STATE(19), 2,
      sym_number,
      sym_symbol,
  [658] = 6,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(95), 1,
      anon_sym_SLASH,
    STATE(19), 1,
      sym_comment,
    ACTIONS(93), 8,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_RPAREN,
      sym__eol,
  [684] = 11,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(15), 1,
      sym__identifier,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(83), 1,
      sym_directive_name,
    ACTIONS(85), 1,
      sym__eol,
    ACTIONS(105), 1,
      ts_builtin_sym_end,
    STATE(20), 1,
      sym_comment,
    STATE(57), 1,
      sym_symbol,
    STATE(95), 1,
      sym__statement,
    STATE(85), 3,
      sym_directive,
      sym_assignment,
      sym_instruction,
  [720] = 6,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(107), 1,
      anon_sym_SLASH,
    STATE(21), 1,
      sym_comment,
    ACTIONS(69), 8,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_RPAREN,
      sym__eol,
  [746] = 7,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(95), 1,
      anon_sym_SLASH,
    STATE(22), 1,
      sym_comment,
    ACTIONS(109), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      sym__eol,
    ACTIONS(93), 4,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
  [773] = 9,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(27), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 1,
      sym__identifier,
    STATE(21), 1,
      sym__sub_expression,
    STATE(23), 1,
      sym_comment,
    ACTIONS(33), 2,
      sym__integer,
      sym__float,
    STATE(19), 3,
      sym__paren_expression,
      sym_number,
      sym_symbol,
  [804] = 10,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(15), 1,
      sym__identifier,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(83), 1,
      sym_directive_name,
    ACTIONS(85), 1,
      sym__eol,
    STATE(24), 1,
      sym_comment,
    STATE(57), 1,
      sym_symbol,
    STATE(110), 1,
      sym__statement,
    STATE(85), 3,
      sym_directive,
      sym_assignment,
      sym_instruction,
  [837] = 9,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(29), 1,
      anon_sym_SQUOTE,
    ACTIONS(31), 1,
      anon_sym_DQUOTE,
    ACTIONS(113), 1,
      sym__identifier,
    STATE(25), 1,
      sym_comment,
    ACTIONS(111), 2,
      sym__integer,
      sym__float,
    STATE(74), 2,
      sym_char,
      sym_string,
  [867] = 7,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(81), 1,
      anon_sym_SLASH,
    STATE(10), 1,
      aux_sym_expression_repeat1,
    STATE(26), 1,
      sym_comment,
    ACTIONS(79), 4,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
  [892] = 9,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(43), 1,
      aux_sym__operand_symbol_token1,
    ACTIONS(115), 1,
      sym__integer,
    ACTIONS(117), 1,
      sym_register,
    STATE(27), 1,
      sym_comment,
    STATE(88), 1,
      sym__operand_symbol,
    STATE(109), 1,
      sym__displacement_expression_offset,
  [920] = 6,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    STATE(28), 1,
      sym_comment,
    ACTIONS(121), 2,
      sym_directive_name,
      sym__identifier,
    ACTIONS(119), 3,
      ts_builtin_sym_end,
      sym_label,
      sym__eol,
  [942] = 9,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(43), 1,
      aux_sym__operand_symbol_token1,
    ACTIONS(115), 1,
      sym__integer,
    ACTIONS(123), 1,
      sym_register,
    STATE(29), 1,
      sym_comment,
    STATE(88), 1,
      sym__operand_symbol,
    STATE(115), 1,
      sym__displacement_expression_offset,
  [970] = 9,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(43), 1,
      aux_sym__operand_symbol_token1,
    ACTIONS(115), 1,
      sym__integer,
    ACTIONS(125), 1,
      anon_sym_LPAREN,
    STATE(30), 1,
      sym_comment,
    STATE(88), 1,
      sym__operand_symbol,
    STATE(119), 1,
      sym__displacement_expression_offset,
  [998] = 5,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    STATE(31), 1,
      sym_comment,
    ACTIONS(127), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym__eol,
  [1018] = 9,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(43), 1,
      aux_sym__operand_symbol_token1,
    ACTIONS(115), 1,
      sym__integer,
    ACTIONS(129), 1,
      sym_register,
    STATE(32), 1,
      sym_comment,
    STATE(88), 1,
      sym__operand_symbol,
    STATE(113), 1,
      sym__displacement_expression_offset,
  [1046] = 6,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    STATE(33), 1,
      sym_comment,
    ACTIONS(133), 2,
      sym_directive_name,
      sym__identifier,
    ACTIONS(131), 3,
      ts_builtin_sym_end,
      sym_label,
      sym__eol,
  [1068] = 9,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(43), 1,
      aux_sym__operand_symbol_token1,
    ACTIONS(115), 1,
      sym__integer,
    ACTIONS(135), 1,
      sym_register,
    STATE(34), 1,
      sym_comment,
    STATE(88), 1,
      sym__operand_symbol,
    STATE(112), 1,
      sym__displacement_expression_offset,
  [1096] = 6,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    STATE(35), 1,
      sym_comment,
    ACTIONS(137), 2,
      sym_directive_name,
      sym__identifier,
    ACTIONS(51), 3,
      ts_builtin_sym_end,
      sym_label,
      sym__eol,
  [1118] = 9,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(43), 1,
      aux_sym__operand_symbol_token1,
    ACTIONS(115), 1,
      sym__integer,
    ACTIONS(139), 1,
      sym_register,
    STATE(36), 1,
      sym_comment,
    STATE(88), 1,
      sym__operand_symbol,
    STATE(124), 1,
      sym__displacement_expression_offset,
  [1146] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(7), 1,
      sym__inline_space,
    ACTIONS(141), 1,
      anon_sym_DQUOTE,
    ACTIONS(143), 1,
      aux_sym_string_token1,
    ACTIONS(145), 1,
      sym__string_escapes,
    STATE(37), 1,
      sym_comment,
    STATE(61), 1,
      aux_sym_string_repeat1,
  [1171] = 7,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(149), 1,
      anon_sym_COMMA,
    STATE(38), 1,
      sym_comment,
    STATE(53), 1,
      aux_sym_instruction_repeat1,
    ACTIONS(147), 2,
      ts_builtin_sym_end,
      sym__eol,
  [1194] = 7,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(7), 1,
      sym__inline_space,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(153), 1,
      anon_sym_STAR_SLASH,
    STATE(39), 1,
      sym_comment,
    STATE(40), 1,
      aux_sym_comment_repeat1,
    ACTIONS(151), 2,
      aux_sym_comment_token2,
      sym__eol,
  [1217] = 6,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(7), 1,
      sym__inline_space,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(158), 1,
      anon_sym_STAR_SLASH,
    ACTIONS(155), 2,
      aux_sym_comment_token2,
      sym__eol,
    STATE(40), 2,
      sym_comment,
      aux_sym_comment_repeat1,
  [1238] = 7,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(7), 1,
      sym__inline_space,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(160), 1,
      anon_sym_STAR_SLASH,
    STATE(39), 1,
      aux_sym_comment_repeat1,
    STATE(41), 1,
      sym_comment,
    ACTIONS(151), 2,
      aux_sym_comment_token2,
      sym__eol,
  [1261] = 7,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(7), 1,
      sym__inline_space,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(162), 1,
      anon_sym_STAR_SLASH,
    STATE(42), 1,
      sym_comment,
    STATE(60), 1,
      aux_sym_comment_repeat1,
    ACTIONS(151), 2,
      aux_sym_comment_token2,
      sym__eol,
  [1284] = 7,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(166), 1,
      anon_sym_COMMA,
    STATE(43), 1,
      sym_comment,
    STATE(62), 1,
      aux_sym_directive_repeat1,
    ACTIONS(164), 2,
      ts_builtin_sym_end,
      sym__eol,
  [1307] = 8,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(43), 1,
      aux_sym__operand_symbol_token1,
    ACTIONS(115), 1,
      sym__integer,
    STATE(44), 1,
      sym_comment,
    STATE(88), 1,
      sym__operand_symbol,
    STATE(118), 1,
      sym__displacement_expression_offset,
  [1332] = 8,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(43), 1,
      aux_sym__operand_symbol_token1,
    ACTIONS(115), 1,
      sym__integer,
    STATE(45), 1,
      sym_comment,
    STATE(88), 1,
      sym__operand_symbol,
    STATE(117), 1,
      sym__displacement_expression_offset,
  [1357] = 8,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(43), 1,
      aux_sym__operand_symbol_token1,
    ACTIONS(115), 1,
      sym__integer,
    STATE(46), 1,
      sym_comment,
    STATE(88), 1,
      sym__operand_symbol,
    STATE(113), 1,
      sym__displacement_expression_offset,
  [1382] = 6,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(168), 1,
      anon_sym_LPAREN,
    STATE(47), 1,
      sym_comment,
    ACTIONS(97), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      sym__eol,
  [1403] = 6,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(172), 1,
      anon_sym_COLON,
    STATE(48), 1,
      sym_comment,
    ACTIONS(170), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      sym__eol,
  [1424] = 7,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(149), 1,
      anon_sym_COMMA,
    STATE(49), 1,
      sym_comment,
    STATE(54), 1,
      aux_sym_instruction_repeat1,
    ACTIONS(174), 2,
      ts_builtin_sym_end,
      sym__eol,
  [1447] = 6,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(176), 1,
      anon_sym_LPAREN,
    STATE(50), 1,
      sym_comment,
    ACTIONS(170), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      sym__eol,
  [1468] = 8,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(43), 1,
      aux_sym__operand_symbol_token1,
    ACTIONS(115), 1,
      sym__integer,
    STATE(51), 1,
      sym_comment,
    STATE(88), 1,
      sym__operand_symbol,
    STATE(109), 1,
      sym__displacement_expression_offset,
  [1493] = 8,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(43), 1,
      aux_sym__operand_symbol_token1,
    ACTIONS(115), 1,
      sym__integer,
    STATE(52), 1,
      sym_comment,
    STATE(88), 1,
      sym__operand_symbol,
    STATE(112), 1,
      sym__displacement_expression_offset,
  [1518] = 6,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(180), 1,
      anon_sym_COMMA,
    ACTIONS(178), 2,
      ts_builtin_sym_end,
      sym__eol,
    STATE(53), 2,
      sym_comment,
      aux_sym_instruction_repeat1,
  [1539] = 7,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(149), 1,
      anon_sym_COMMA,
    STATE(53), 1,
      aux_sym_instruction_repeat1,
    STATE(54), 1,
      sym_comment,
    ACTIONS(183), 2,
      ts_builtin_sym_end,
      sym__eol,
  [1562] = 7,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(149), 1,
      anon_sym_COMMA,
    STATE(38), 1,
      aux_sym_instruction_repeat1,
    STATE(55), 1,
      sym_comment,
    ACTIONS(183), 2,
      ts_builtin_sym_end,
      sym__eol,
  [1585] = 6,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(187), 1,
      anon_sym_COMMA,
    ACTIONS(185), 2,
      ts_builtin_sym_end,
      sym__eol,
    STATE(56), 2,
      sym_comment,
      aux_sym_directive_repeat1,
  [1606] = 7,
    ACTIONS(192), 1,
      anon_sym_EQ,
    ACTIONS(194), 1,
      aux_sym_comment_token1,
    ACTIONS(196), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(198), 1,
      sym__inline_space,
    STATE(57), 1,
      sym_comment,
    STATE(96), 1,
      aux_sym_assignment_repeat1,
    ACTIONS(190), 2,
      ts_builtin_sym_end,
      sym__eol,
  [1629] = 6,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(202), 1,
      anon_sym_SQUOTE,
    STATE(58), 1,
      sym_comment,
    ACTIONS(200), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      sym__eol,
  [1650] = 7,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(7), 1,
      sym__inline_space,
    ACTIONS(204), 1,
      anon_sym_DQUOTE,
    ACTIONS(206), 1,
      aux_sym_string_token1,
    ACTIONS(209), 1,
      sym__string_escapes,
    STATE(59), 2,
      sym_comment,
      aux_sym_string_repeat1,
  [1673] = 7,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(7), 1,
      sym__inline_space,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(212), 1,
      anon_sym_STAR_SLASH,
    STATE(40), 1,
      aux_sym_comment_repeat1,
    STATE(60), 1,
      sym_comment,
    ACTIONS(151), 2,
      aux_sym_comment_token2,
      sym__eol,
  [1696] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(7), 1,
      sym__inline_space,
    ACTIONS(143), 1,
      aux_sym_string_token1,
    ACTIONS(145), 1,
      sym__string_escapes,
    ACTIONS(214), 1,
      anon_sym_DQUOTE,
    STATE(59), 1,
      aux_sym_string_repeat1,
    STATE(61), 1,
      sym_comment,
  [1721] = 7,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(166), 1,
      anon_sym_COMMA,
    STATE(56), 1,
      aux_sym_directive_repeat1,
    STATE(62), 1,
      sym_comment,
    ACTIONS(216), 2,
      ts_builtin_sym_end,
      sym__eol,
  [1744] = 5,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    STATE(63), 1,
      sym_comment,
    ACTIONS(218), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      sym__eol,
  [1762] = 5,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    STATE(64), 1,
      sym_comment,
    ACTIONS(220), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      sym__eol,
  [1780] = 5,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    STATE(65), 1,
      sym_comment,
    ACTIONS(109), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      sym__eol,
  [1798] = 5,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    STATE(66), 1,
      sym_comment,
    ACTIONS(222), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      sym__eol,
  [1816] = 5,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    STATE(67), 1,
      sym_comment,
    ACTIONS(224), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      sym__eol,
  [1834] = 5,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    STATE(68), 1,
      sym_comment,
    ACTIONS(226), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      sym__eol,
  [1852] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(7), 1,
      sym__inline_space,
    ACTIONS(230), 1,
      aux_sym_string_token1,
    STATE(69), 1,
      sym_comment,
    ACTIONS(228), 2,
      anon_sym_DQUOTE,
      sym__string_escapes,
  [1872] = 5,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    STATE(70), 1,
      sym_comment,
    ACTIONS(232), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      sym__eol,
  [1890] = 5,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    STATE(71), 1,
      sym_comment,
    ACTIONS(234), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      sym__eol,
  [1908] = 5,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    STATE(72), 1,
      sym_comment,
    ACTIONS(170), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      sym__eol,
  [1926] = 5,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    STATE(73), 1,
      sym_comment,
    ACTIONS(236), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      sym__eol,
  [1944] = 5,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    STATE(74), 1,
      sym_comment,
    ACTIONS(238), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      sym__eol,
  [1962] = 2,
    STATE(75), 1,
      sym_comment,
    ACTIONS(101), 6,
      ts_builtin_sym_end,
      anon_sym_EQ,
      aux_sym_comment_token1,
      anon_sym_SLASH_STAR,
      sym__inline_space,
      sym__eol,
  [1974] = 5,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    STATE(76), 1,
      sym_comment,
    ACTIONS(240), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      sym__eol,
  [1992] = 5,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    STATE(77), 1,
      sym_comment,
    ACTIONS(242), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      sym__eol,
  [2010] = 5,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    STATE(78), 1,
      sym_comment,
    ACTIONS(178), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      sym__eol,
  [2028] = 6,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(7), 1,
      sym__inline_space,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(246), 1,
      anon_sym_STAR_SLASH,
    STATE(79), 1,
      sym_comment,
    ACTIONS(244), 2,
      aux_sym_comment_token2,
      sym__eol,
  [2048] = 5,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    STATE(80), 1,
      sym_comment,
    ACTIONS(248), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      sym__eol,
  [2066] = 5,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    STATE(81), 1,
      sym_comment,
    ACTIONS(250), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      sym__eol,
  [2084] = 5,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    STATE(82), 1,
      sym_comment,
    ACTIONS(185), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      sym__eol,
  [2102] = 5,
    ACTIONS(252), 1,
      anon_sym_EQ,
    ACTIONS(254), 1,
      aux_sym_comment_token1,
    ACTIONS(257), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(260), 1,
      sym__inline_space,
    STATE(83), 2,
      sym_comment,
      aux_sym_assignment_repeat1,
  [2119] = 6,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(263), 1,
      anon_sym_COMMA,
    ACTIONS(265), 1,
      sym_register,
    STATE(84), 1,
      sym_comment,
  [2138] = 5,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    STATE(85), 1,
      sym_comment,
    ACTIONS(267), 2,
      ts_builtin_sym_end,
      sym__eol,
  [2155] = 5,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    STATE(86), 1,
      sym_comment,
    ACTIONS(168), 2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [2172] = 6,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(269), 1,
      anon_sym_COMMA,
    ACTIONS(271), 1,
      anon_sym_RPAREN,
    STATE(87), 1,
      sym_comment,
  [2191] = 5,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    STATE(88), 1,
      sym_comment,
    ACTIONS(176), 2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [2208] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(7), 1,
      sym__inline_space,
    ACTIONS(273), 1,
      aux_sym_char_token1,
    ACTIONS(275), 1,
      sym__character_escapes,
    STATE(89), 1,
      sym_comment,
  [2227] = 6,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(65), 1,
      ts_builtin_sym_end,
    ACTIONS(85), 1,
      sym__eol,
    STATE(90), 1,
      sym_comment,
  [2246] = 6,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(277), 1,
      anon_sym_COMMA,
    ACTIONS(279), 1,
      sym_register,
    STATE(91), 1,
      sym_comment,
  [2265] = 6,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(85), 1,
      sym__eol,
    ACTIONS(105), 1,
      ts_builtin_sym_end,
    STATE(92), 1,
      sym_comment,
  [2284] = 5,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    STATE(93), 1,
      sym_comment,
    ACTIONS(281), 2,
      ts_builtin_sym_end,
      sym__eol,
  [2301] = 6,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(271), 1,
      anon_sym_RPAREN,
    ACTIONS(277), 1,
      anon_sym_COMMA,
    STATE(94), 1,
      sym_comment,
  [2320] = 6,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(283), 1,
      ts_builtin_sym_end,
    ACTIONS(285), 1,
      sym__eol,
    STATE(95), 1,
      sym_comment,
  [2339] = 6,
    ACTIONS(194), 1,
      aux_sym_comment_token1,
    ACTIONS(196), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(287), 1,
      anon_sym_EQ,
    ACTIONS(289), 1,
      sym__inline_space,
    STATE(83), 1,
      aux_sym_assignment_repeat1,
    STATE(96), 1,
      sym_comment,
  [2358] = 6,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(291), 1,
      anon_sym_COMMA,
    ACTIONS(293), 1,
      anon_sym_RPAREN,
    STATE(97), 1,
      sym_comment,
  [2377] = 6,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(295), 1,
      anon_sym_COMMA,
    ACTIONS(297), 1,
      anon_sym_RPAREN,
    STATE(98), 1,
      sym_comment,
  [2396] = 6,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(299), 1,
      anon_sym_COMMA,
    ACTIONS(301), 1,
      sym_register,
    STATE(99), 1,
      sym_comment,
  [2415] = 6,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(293), 1,
      anon_sym_RPAREN,
    ACTIONS(303), 1,
      anon_sym_COMMA,
    STATE(100), 1,
      sym_comment,
  [2434] = 6,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(303), 1,
      anon_sym_COMMA,
    ACTIONS(305), 1,
      sym_register,
    STATE(101), 1,
      sym_comment,
  [2453] = 6,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(105), 1,
      ts_builtin_sym_end,
    ACTIONS(285), 1,
      sym__eol,
    STATE(102), 1,
      sym_comment,
  [2472] = 5,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(309), 1,
      sym__inline_space,
    STATE(103), 1,
      sym_comment,
    ACTIONS(307), 2,
      ts_builtin_sym_end,
      sym__eol,
  [2489] = 5,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    STATE(104), 1,
      sym_comment,
    ACTIONS(311), 2,
      ts_builtin_sym_end,
      sym__eol,
  [2506] = 6,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(313), 1,
      anon_sym_COMMA,
    ACTIONS(315), 1,
      anon_sym_RPAREN,
    STATE(105), 1,
      sym_comment,
  [2525] = 6,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(317), 1,
      anon_sym_COMMA,
    ACTIONS(319), 1,
      anon_sym_RPAREN,
    STATE(106), 1,
      sym_comment,
  [2544] = 6,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(315), 1,
      anon_sym_RPAREN,
    ACTIONS(321), 1,
      anon_sym_COMMA,
    STATE(107), 1,
      sym_comment,
  [2563] = 6,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(263), 1,
      anon_sym_COMMA,
    ACTIONS(323), 1,
      anon_sym_RPAREN,
    STATE(108), 1,
      sym_comment,
  [2582] = 5,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(319), 1,
      anon_sym_RPAREN,
    STATE(109), 1,
      sym_comment,
  [2598] = 5,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(285), 1,
      sym__eol,
    STATE(110), 1,
      sym_comment,
  [2614] = 5,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(325), 1,
      anon_sym_LPAREN,
    STATE(111), 1,
      sym_comment,
  [2630] = 5,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(315), 1,
      anon_sym_RPAREN,
    STATE(112), 1,
      sym_comment,
  [2646] = 5,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(297), 1,
      anon_sym_RPAREN,
    STATE(113), 1,
      sym_comment,
  [2662] = 5,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(327), 1,
      ts_builtin_sym_end,
    STATE(114), 1,
      sym_comment,
  [2678] = 5,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(293), 1,
      anon_sym_RPAREN,
    STATE(115), 1,
      sym_comment,
  [2694] = 5,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(85), 1,
      sym__eol,
    STATE(116), 1,
      sym_comment,
  [2710] = 5,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(329), 1,
      anon_sym_RPAREN,
    STATE(117), 1,
      sym_comment,
  [2726] = 5,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(331), 1,
      anon_sym_RPAREN,
    STATE(118), 1,
      sym_comment,
  [2742] = 5,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(333), 1,
      anon_sym_LPAREN,
    STATE(119), 1,
      sym_comment,
  [2758] = 2,
    STATE(120), 1,
      sym_comment,
    ACTIONS(335), 4,
      anon_sym_EQ,
      aux_sym_comment_token1,
      anon_sym_SLASH_STAR,
      sym__inline_space,
  [2768] = 5,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(337), 1,
      anon_sym_RPAREN,
    STATE(121), 1,
      sym_comment,
  [2784] = 2,
    STATE(122), 1,
      sym_comment,
    ACTIONS(339), 4,
      anon_sym_EQ,
      aux_sym_comment_token1,
      anon_sym_SLASH_STAR,
      sym__inline_space,
  [2794] = 2,
    STATE(123), 1,
      sym_comment,
    ACTIONS(341), 4,
      anon_sym_EQ,
      aux_sym_comment_token1,
      anon_sym_SLASH_STAR,
      sym__inline_space,
  [2804] = 5,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(271), 1,
      anon_sym_RPAREN,
    STATE(124), 1,
      sym_comment,
  [2820] = 5,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      sym__inline_space,
    ACTIONS(343), 1,
      sym__identifier,
    STATE(125), 1,
      sym_comment,
  [2836] = 1,
    ACTIONS(339), 1,
      ts_builtin_sym_end,
  [2840] = 1,
    ACTIONS(341), 1,
      ts_builtin_sym_end,
  [2844] = 1,
    ACTIONS(335), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 56,
  [SMALL_STATE(4)] = 109,
  [SMALL_STATE(5)] = 162,
  [SMALL_STATE(6)] = 215,
  [SMALL_STATE(7)] = 266,
  [SMALL_STATE(8)] = 306,
  [SMALL_STATE(9)] = 348,
  [SMALL_STATE(10)] = 377,
  [SMALL_STATE(11)] = 408,
  [SMALL_STATE(12)] = 444,
  [SMALL_STATE(13)] = 480,
  [SMALL_STATE(14)] = 506,
  [SMALL_STATE(15)] = 534,
  [SMALL_STATE(16)] = 570,
  [SMALL_STATE(17)] = 596,
  [SMALL_STATE(18)] = 622,
  [SMALL_STATE(19)] = 658,
  [SMALL_STATE(20)] = 684,
  [SMALL_STATE(21)] = 720,
  [SMALL_STATE(22)] = 746,
  [SMALL_STATE(23)] = 773,
  [SMALL_STATE(24)] = 804,
  [SMALL_STATE(25)] = 837,
  [SMALL_STATE(26)] = 867,
  [SMALL_STATE(27)] = 892,
  [SMALL_STATE(28)] = 920,
  [SMALL_STATE(29)] = 942,
  [SMALL_STATE(30)] = 970,
  [SMALL_STATE(31)] = 998,
  [SMALL_STATE(32)] = 1018,
  [SMALL_STATE(33)] = 1046,
  [SMALL_STATE(34)] = 1068,
  [SMALL_STATE(35)] = 1096,
  [SMALL_STATE(36)] = 1118,
  [SMALL_STATE(37)] = 1146,
  [SMALL_STATE(38)] = 1171,
  [SMALL_STATE(39)] = 1194,
  [SMALL_STATE(40)] = 1217,
  [SMALL_STATE(41)] = 1238,
  [SMALL_STATE(42)] = 1261,
  [SMALL_STATE(43)] = 1284,
  [SMALL_STATE(44)] = 1307,
  [SMALL_STATE(45)] = 1332,
  [SMALL_STATE(46)] = 1357,
  [SMALL_STATE(47)] = 1382,
  [SMALL_STATE(48)] = 1403,
  [SMALL_STATE(49)] = 1424,
  [SMALL_STATE(50)] = 1447,
  [SMALL_STATE(51)] = 1468,
  [SMALL_STATE(52)] = 1493,
  [SMALL_STATE(53)] = 1518,
  [SMALL_STATE(54)] = 1539,
  [SMALL_STATE(55)] = 1562,
  [SMALL_STATE(56)] = 1585,
  [SMALL_STATE(57)] = 1606,
  [SMALL_STATE(58)] = 1629,
  [SMALL_STATE(59)] = 1650,
  [SMALL_STATE(60)] = 1673,
  [SMALL_STATE(61)] = 1696,
  [SMALL_STATE(62)] = 1721,
  [SMALL_STATE(63)] = 1744,
  [SMALL_STATE(64)] = 1762,
  [SMALL_STATE(65)] = 1780,
  [SMALL_STATE(66)] = 1798,
  [SMALL_STATE(67)] = 1816,
  [SMALL_STATE(68)] = 1834,
  [SMALL_STATE(69)] = 1852,
  [SMALL_STATE(70)] = 1872,
  [SMALL_STATE(71)] = 1890,
  [SMALL_STATE(72)] = 1908,
  [SMALL_STATE(73)] = 1926,
  [SMALL_STATE(74)] = 1944,
  [SMALL_STATE(75)] = 1962,
  [SMALL_STATE(76)] = 1974,
  [SMALL_STATE(77)] = 1992,
  [SMALL_STATE(78)] = 2010,
  [SMALL_STATE(79)] = 2028,
  [SMALL_STATE(80)] = 2048,
  [SMALL_STATE(81)] = 2066,
  [SMALL_STATE(82)] = 2084,
  [SMALL_STATE(83)] = 2102,
  [SMALL_STATE(84)] = 2119,
  [SMALL_STATE(85)] = 2138,
  [SMALL_STATE(86)] = 2155,
  [SMALL_STATE(87)] = 2172,
  [SMALL_STATE(88)] = 2191,
  [SMALL_STATE(89)] = 2208,
  [SMALL_STATE(90)] = 2227,
  [SMALL_STATE(91)] = 2246,
  [SMALL_STATE(92)] = 2265,
  [SMALL_STATE(93)] = 2284,
  [SMALL_STATE(94)] = 2301,
  [SMALL_STATE(95)] = 2320,
  [SMALL_STATE(96)] = 2339,
  [SMALL_STATE(97)] = 2358,
  [SMALL_STATE(98)] = 2377,
  [SMALL_STATE(99)] = 2396,
  [SMALL_STATE(100)] = 2415,
  [SMALL_STATE(101)] = 2434,
  [SMALL_STATE(102)] = 2453,
  [SMALL_STATE(103)] = 2472,
  [SMALL_STATE(104)] = 2489,
  [SMALL_STATE(105)] = 2506,
  [SMALL_STATE(106)] = 2525,
  [SMALL_STATE(107)] = 2544,
  [SMALL_STATE(108)] = 2563,
  [SMALL_STATE(109)] = 2582,
  [SMALL_STATE(110)] = 2598,
  [SMALL_STATE(111)] = 2614,
  [SMALL_STATE(112)] = 2630,
  [SMALL_STATE(113)] = 2646,
  [SMALL_STATE(114)] = 2662,
  [SMALL_STATE(115)] = 2678,
  [SMALL_STATE(116)] = 2694,
  [SMALL_STATE(117)] = 2710,
  [SMALL_STATE(118)] = 2726,
  [SMALL_STATE(119)] = 2742,
  [SMALL_STATE(120)] = 2758,
  [SMALL_STATE(121)] = 2768,
  [SMALL_STATE(122)] = 2784,
  [SMALL_STATE(123)] = 2794,
  [SMALL_STATE(124)] = 2804,
  [SMALL_STATE(125)] = 2820,
  [SMALL_STATE(126)] = 2836,
  [SMALL_STATE(127)] = 2840,
  [SMALL_STATE(128)] = 2844,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT(128),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(103),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_directive_repeat1, 1),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_assignment_repeat1, 1),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(24),
  [56] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(103),
  [59] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(75),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(33),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 2),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 2), SHIFT_REPEAT(23),
  [74] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expression_repeat1, 2), SHIFT_REPEAT(23),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 2),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__paren_expression, 3),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__paren_expression, 3),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__sub_expression, 1),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__sub_expression, 1),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbol, 1),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_symbol, 1),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_expression_repeat1, 2),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__directive_arg, 1),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 3),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 3),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__operand_symbol, 1),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [143] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 5, .production_id = 1),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [151] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [155] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2), SHIFT_REPEAT(79),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_comment_repeat1, 2),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 3),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__displacement_expression_offset, 1, .production_id = 2),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__operand, 1),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 3, .production_id = 1),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__displacement_expression_offset, 1),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_instruction_repeat1, 2),
  [180] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_instruction_repeat1, 2), SHIFT_REPEAT(4),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 4, .production_id = 1),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_directive_repeat1, 2),
  [187] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_directive_repeat1, 2), SHIFT_REPEAT(2),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 1, .production_id = 1),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_char, 2),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2),
  [206] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(69),
  [209] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(69),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 4),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__displacement_expression, 3),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 2),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__displacement_expression, 10),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__displacement_expression, 9),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 1),
  [230] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 1),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__displacement_expression, 8),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__displacement_expression, 7),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__displacement_expression, 6),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constant, 2),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__displacement_expression, 5),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__displacement_expression, 4),
  [244] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 1),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_comment_repeat1, 1),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_char, 3),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_assignment_repeat1, 2),
  [254] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_assignment_repeat1, 2), SHIFT_REPEAT(120),
  [257] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_assignment_repeat1, 2), SHIFT_REPEAT(41),
  [260] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_assignment_repeat1, 2), SHIFT_REPEAT(83),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 1),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [273] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3),
  [283] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [307] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 1),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [311] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 4),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [327] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [335] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [339] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2),
  [341] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_YOUR_LANGUAGE_NAME(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
